In [3]:
import pandas as pd

In [4]:
new_york_tree_census_2015_dataset = "../dramane/new_york_tree_census_2015.csv"
new_york_tree_census_2015_df = pd.read_csv(new_york_tree_census_2015_dataset)
new_york_tree_census_2015_df.head()

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,st_assem,st_senate,nta,nta_name,boro_ct,state,latitude,longitude,x_sp,y_sp
0,606945,305778,2016-06-28,10,0,OnCurb,Alive,Good,Fraxinus pennsylvanica,green ash,...,25,14,QN37,Kew Gardens Hills,4125700,New York,40.724339,-73.805180,1.038250e+06,203232.9417
1,160321,341273,2015-08-19,9,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,34,13,QN28,Jackson Heights,4030902,New York,40.756626,-73.894167,1.013571e+06,214953.6472
2,541347,325281,2015-12-30,7,0,OnCurb,Alive,Good,Pyrus calleryana,Callery pear,...,32,10,QN76,Baisley Park,4028800,New York,40.679777,-73.788463,1.042923e+06,187008.2671
3,613930,203822,2016-07-05,10,0,OnCurb,Alive,Good,Pyrus calleryana,Callery pear,...,46,22,BK31,Bay Ridge,3005000,New York,40.622743,-74.037543,9.738279e+05,166160.5847
4,18353,338911,2015-06-13,4,0,OnCurb,Alive,Good,Prunus virginiana,'Schubert' chokecherry,...,31,10,QN12,Hammels-Arverne-Edgemere,4095400,New York,40.596514,-73.797622,1.040452e+06,156667.5017

In [5]:
new_new_york_tree_census_2015_df = new_york_tree_census_2015_df[['tree_id','block_id', 'status','health', 'spc_latin']]

new_new_york_tree_census_2015_df

        tree_id  block_id status health                           spc_latin
0        606945    305778  Alive   Good              Fraxinus pennsylvanica
1        160321    341273  Alive   Good  Gleditsia triacanthos var. inermis
2        541347    325281  Alive   Good                    Pyrus calleryana
3        613930    203822  Alive   Good                    Pyrus calleryana
4         18353    338911  Alive   Good                   Prunus virginiana
...         ...       ...    ...    ...                                 ...
683783   237788    223344  Alive   Poor                   Prunus cerasifera
683784   249489    335314   Dead    NaN                                 NaN
683785   230261    230303   Dead    NaN                                 NaN
683786   623784    318368  Alive   Good                       Quercus rubra
683787   139749    217836  Alive   Good                     Zelkova serrata

[683788 rows x 5 columns]

In [6]:
new_new_york_tree_census_2015_df['spc_latin_for_join']=new_new_york_tree_census_2015_df['spc_latin'].str.strip()

new_new_york_tree_census_2015_df['spc_latin_for_join']=new_new_york_tree_census_2015_df['spc_latin_for_join'].str.replace(" ",'')
new_new_york_tree_census_2015_df['spc_latin_for_join']=new_new_york_tree_census_2015_df['spc_latin_for_join'].str.lower()
new_new_york_tree_census_2015_df.sample(10)

<ipython-input-6-e14aac06183a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_new_york_tree_census_2015_df['spc_latin_for_join']=new_new_york_tree_census_2015_df['spc_latin'].str.strip()
<ipython-input-6-e14aac06183a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_new_york_tree_census_2015_df['spc_latin_for_join']=new_new_york_tree_census_2015_df['spc_latin_for_join'].str.replace(" ",'')
<ipython-input-6-e14aac06183a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_new_york_tree_census_2015_df['spc_latin_for_join']=new_new_york_tree_census_2015_df['spc_latin_for_join'].str.lower()

,tree_id,block_id,status,health,spc_latin,spc_latin_for_join
187593,685512,308067,Alive,Good,Fraxinus,fraxinus
114982,292152,104083,Alive,Fair,Gleditsia triacanthos var. inermis,gleditsiatriacanthosvar.inermis
434824,314930,303685,Alive,Good,Gleditsia triacanthos var. inermis,gleditsiatriacanthosvar.inermis
613166,610694,324670,Alive,Good,Acer,acer
428244,127388,221256,Alive,Good,Syringa reticulata,syringareticulata
142099,627275,346000,Alive,Good,Prunus,prunus
19724,216242,342603,Alive,Good,Gleditsia triacanthos var. inermis,gleditsiatriacanthosvar.inermis
656706,653360,331123,Alive,Fair,Prunus,prunus
358395,494188,342050,Alive,Fair,Syringa reticulata,syringareticulata
50790,26311,344438,Alive,Good,Acer platanoides,acerplatanoides

In [7]:
chars = "\`*_{}[]()>#+-.,!$:;%'&/?"
for c in chars:
    new_new_york_tree_census_2015_df['spc_latin_for_join'] = new_new_york_tree_census_2015_df['spc_latin_for_join'].str.replace(c,"")

new_new_york_tree_census_2015_df

<ipython-input-7-1758ca78d1d1>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_new_york_tree_census_2015_df['spc_latin_for_join'] = new_new_york_tree_census_2015_df['spc_latin_for_join'].str.replace(c,"")

,tree_id,block_id,status,health,spc_latin,spc_latin_for_join
0,606945,305778,Alive,Good,Fraxinus pennsylvanica,fraxinuspennsylvanica
1,160321,341273,Alive,Good,Gleditsia triacanthos var. inermis,gleditsiatriacanthosvarinermis
2,541347,325281,Alive,Good,Pyrus calleryana,pyruscalleryana
3,613930,203822,Alive,Good,Pyrus calleryana,pyruscalleryana
4,18353,338911,Alive,Good,Prunus virginiana,prunusvirginiana
...,...,...,...,...,...,...
683783,237788,223344,Alive,Poor,Prunus cerasifera,prunuscerasifera
683784,249489,335314,Dead,NaN,NaN,NaN
683785,230261,230303,Dead,NaN,NaN,NaN
683786,623784,318368,Alive,Good,Quercus rubra,quercusrubra
683787,139749,217836,Alive,Good,Zelkova serrata,zelkovaserrata

In [8]:
clean_new_york_tree_census_2015_df = new_new_york_tree_census_2015_df.drop_duplicates()
clean_new_york_tree_census_2015_df.head(20)

,tree_id,block_id,status,health,spc_latin,spc_latin_for_join
0,606945,305778,Alive,Good,Fraxinus pennsylvanica,fraxinuspennsylvanica
1,160321,341273,Alive,Good,Gleditsia triacanthos var. inermis,gleditsiatriacanthosvarinermis
2,541347,325281,Alive,Good,Pyrus calleryana,pyruscalleryana
3,613930,203822,Alive,Good,Pyrus calleryana,pyruscalleryana
4,18353,338911,Alive,Good,Prunus virginiana,prunusvirginiana
5,21173,108713,Alive,Good,Gleditsia triacanthos var. inermis,gleditsiatriacanthosvarinermis
6,544698,201434,Alive,Fair,Quercus rubra,quercusrubra
7,546240,228778,Alive,Good,Tilia americana,tiliaamericana
8,646348,309729,Alive,Good,Quercus palustris,quercuspalustris
9,413812,501196,Alive,Good,Ulmus americana,ulmusamericana
10,643898,308820,Alive,Good,Platanus x acerifolia,platanusxacerifolia
11,51527,414908,Alive,Good,Pyrus calleryana,pyruscalleryana
12,111516,103671,Alive,Good,Tilia americana,tiliaamericana
13,316742,413488,Alive,Good,Acer saccharinum,acersaccharinum
14,428425,222536,Dead,NaN,NaN,NaN
15,581674,330418,Alive,Good,Gleditsia triacanthos var. inermis,gleditsiatriacanthosvarinermis
16,341736,510883,Dead,NaN,NaN,NaN
17,545989,212884,Alive,Good,Fraxinus americana,fraxinusamericana
18,386593,400007,Alive,Fair,Quercus rubra,quercusrubra
19,10288,219608,Alive,Fair,Crataegus,crataegus

In [9]:

clean_new_york_tree_census_2015_df.to_csv(r'../dramane/clean_new_york_tree_census_2015_data.csv', index = False)