In [1]:
import pandas as pd
import numpy as np

In [2]:
#import csv
real_estate_file = 'data/nyc_real_estate_building_final_use_this.csv'
real_estate_df = pd.read_csv(real_estate_file)


real_estate_df

,index,full_address,building_class_category,sale_price,neighborhood,tax_class_at_present,zip_code,building_class_at_time_of_sale,borough_name,latitude,longitude
0,0,****** 95TH STREET Queens,07 RENTALS - WALKUP APARTMENTS,0.0,OZONE PARK,1B,11417.0,V0,Queens,40.686989,-73.847231
1,2,1 5 AVENUE Manhattan,07 RENTALS - WALKUP APARTMENTS,4925000.0,GREENWICH VILLAGE-CENTRAL,2,10003.0,D4,Manhattan,49.836689,24.020745
2,3,1 5TH AVENUE Manhattan,07 RENTALS - WALKUP APARTMENTS,0.0,GREENWICH VILLAGE-CENTRAL,2,10003.0,D4,Manhattan,40.745898,-73.986688
3,4,1 ASCAN AVE Queens,07 RENTALS - WALKUP APARTMENTS,649000.0,FOREST HILLS,2,11375.0,D4,Queens,40.717455,-73.841313
4,5,1 ASCAN AVENUE Queens,07 RENTALS - WALKUP APARTMENTS,395000.0,FOREST HILLS,2,11375.0,D4,Queens,40.717455,-73.841313
...,...,...,...,...,...,...,...,...,...,...,...
55737,58586,WOODROW ROAD Staten Island,13 CONDOS - ELEVATOR APARTMENTS,0.0,ARDEN HEIGHTS,1B,10312.0,V0,Staten Island,40.546672,-74.191896
55738,58587,WOODYCREST AVENUE Bronx,13 CONDOS - ELEVATOR APARTMENTS,750000.0,HIGHBRIDGE/MORRIS HEIGHTS,4,0.0,G7,Bronx,40.830083,-73.929969
55739,58588,WORTMAN AVENUE Brooklyn,13 CONDOS - ELEVATOR APARTMENTS,0.0,EAST NEW YORK,4,0.0,G7,Brooklyn,40.661459,-73.874470
55740,58589,YORK AVENUE Staten Island,13 CONDOS - ELEVATOR APARTMENTS,235000.0,NEW BRIGHTON,1B,10301.0,V0,Staten Island,40.642265,-74.087684
55741,58590,ZEREGA AVENUE Bronx,13 CONDOS - ELEVATOR APARTMENTS,5000000.0,CASTLE HILL/UNIONPORT,4,10473.0,V1,Bronx,40.836779,-73.846690

In [10]:
#breaking out by borough

manhattan_df = real_estate_df.loc[real_estate_df['borough_name'] == 'Manhattan']

manhattan_bulding_df = pd.DataFrame(manhattan_df['building_class_category'].value_counts())

manhattan_bulding_df.reset_index(drop=False)

manhattan_bulding_df

                                              building_class_category
13 CONDOS - ELEVATOR APARTMENTS                                  1097
10 COOPS - ELEVATOR APARTMENTS                                   1059
02 TWO FAMILY DWELLINGS                                          1051
01 ONE FAMILY DWELLINGS                                           700
03 THREE FAMILY DWELLINGS                                         425
07 RENTALS - WALKUP APARTMENTS                                    379
09 COOPS - WALKUP APARTMENTS                                      176
15 CONDOS - 2-10 UNIT RESIDENTIAL                                 137
44 CONDO PARKING                                                  100
04 TAX CLASS 1 CONDOS                                              94
22 STORE BUILDINGS                                                 85
17 CONDO COOPS                                                     78
05 TAX CLASS 1 VACANT LAND                                         63
12 CONDOS - WALKUP APARTMENTS                                      59
29 COMMERCIAL GARAGES                                              57
08 RENTALS - ELEVATOR APARTMENTS                                   46
31 COMMERCIAL VACANT LAND                                          44
14 RENTALS - 4-10 UNIT                                             38
21 OFFICE BUILDINGS                                                36
47 CONDO NON-BUSINESS STORAGE                                      35
43 CONDO OFFICE BUILDINGS                                          27
45 CONDO HOTELS                                                    26
30 WAREHOUSES                                                      22
06 TAX CLASS 1 - OTHER                                             21
26 OTHER HOTELS                                                    19
41 TAX CLASS 4 - OTHER                                             18
27 FACTORIES                                                       17
46 CONDO STORE BUILDINGS                                           10
37 RELIGIOUS FACILITIES                                             9
16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT                          6
32 HOSPITAL AND HEALTH FACILITIES                                   5
48 CONDO TERRACES/GARDENS/CABANAS                                   5
33 EDUCATIONAL FACILITIES                                           5
38 ASYLUMS AND HOMES                                                4
23 LOFT BUILDINGS                                                   3
35 INDOOR PUBLIC AND CULTURAL FACILITIES                            3
34 THEATRES                                                         3
18 TAX CLASS 3 - UNTILITY PROPERTIES                                3
11A CONDO-RENTALS                                                   3
39 TRANSPORTATION FACILITIES                                        1
11 SPECIAL CONDO BILLING LOTS                                       1
49 CONDO WAREHOUSES/FACTORY/INDUS                                   1

In [11]:
#breaking out by borough

queens_df = real_estate_df.loc[real_estate_df['borough_name'] == 'Queens']

queens_bulding_df = pd.DataFrame(queens_df['building_class_category'].value_counts())

queens_bulding_df.rename(columns={"Index": "Type of Building"})

queens_bulding_df

                                              building_class_category
13 CONDOS - ELEVATOR APARTMENTS                                  4500
10 COOPS - ELEVATOR APARTMENTS                                   3792
02 TWO FAMILY DWELLINGS                                          3321
01 ONE FAMILY DWELLINGS                                          2842
03 THREE FAMILY DWELLINGS                                        1074
07 RENTALS - WALKUP APARTMENTS                                    938
09 COOPS - WALKUP APARTMENTS                                      598
17 CONDO COOPS                                                    524
15 CONDOS - 2-10 UNIT RESIDENTIAL                                 378
04 TAX CLASS 1 CONDOS                                             246
12 CONDOS - WALKUP APARTMENTS                                     230
22 STORE BUILDINGS                                                205
44 CONDO PARKING                                                  191
14 RENTALS - 4-10 UNIT                                            176
05 TAX CLASS 1 VACANT LAND                                        140
43 CONDO OFFICE BUILDINGS                                         125
08 RENTALS - ELEVATOR APARTMENTS                                  117
31 COMMERCIAL VACANT LAND                                         115
21 OFFICE BUILDINGS                                               109
45 CONDO HOTELS                                                   101
29 COMMERCIAL GARAGES                                              93
47 CONDO NON-BUSINESS STORAGE                                      80
30 WAREHOUSES                                                      71
27 FACTORIES                                                       54
46 CONDO STORE BUILDINGS                                           47
41 TAX CLASS 4 - OTHER                                             46
49 CONDO WAREHOUSES/FACTORY/INDUS                                  25
37 RELIGIOUS FACILITIES                                            25
16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT                         22
06 TAX CLASS 1 - OTHER                                             20
11A CONDO-RENTALS                                                  19
23 LOFT BUILDINGS                                                  19
48 CONDO TERRACES/GARDENS/CABANAS                                  19
32 HOSPITAL AND HEALTH FACILITIES                                  17
28 COMMERCIAL CONDOS                                               12
26 OTHER HOTELS                                                    10
38 ASYLUMS AND HOMES                                                5
36 OUTDOOR RECREATIONAL FACILITIES                                  5
35 INDOOR PUBLIC AND CULTURAL FACILITIES                            5
33 EDUCATIONAL FACILITIES                                           5
34 THEATRES                                                         4
42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC                           4
25 LUXURY HOTELS                                                    1
39 TRANSPORTATION FACILITIES                                        1

In [12]:
#breaking out by borough

brooklyn_df = real_estate_df.loc[real_estate_df['borough_name'] == 'Brooklyn']

brooklyn_bulding_df = pd.DataFrame(brooklyn_df['building_class_category'].value_counts())

brooklyn_bulding_df.rename(columns={"Index": "Type of Building"})

brooklyn_bulding_df

                                              building_class_category
13 CONDOS - ELEVATOR APARTMENTS                                  3308
10 COOPS - ELEVATOR APARTMENTS                                   3003
02 TWO FAMILY DWELLINGS                                          2897
01 ONE FAMILY DWELLINGS                                          2138
03 THREE FAMILY DWELLINGS                                        1103
07 RENTALS - WALKUP APARTMENTS                                    848
09 COOPS - WALKUP APARTMENTS                                      502
15 CONDOS - 2-10 UNIT RESIDENTIAL                                 406
44 CONDO PARKING                                                  356
04 TAX CLASS 1 CONDOS                                             340
17 CONDO COOPS                                                    246
05 TAX CLASS 1 VACANT LAND                                        223
14 RENTALS - 4-10 UNIT                                            179
22 STORE BUILDINGS                                                175
29 COMMERCIAL GARAGES                                             155
12 CONDOS - WALKUP APARTMENTS                                     141
47 CONDO NON-BUSINESS STORAGE                                     131
43 CONDO OFFICE BUILDINGS                                         106
08 RENTALS - ELEVATOR APARTMENTS                                   99
31 COMMERCIAL VACANT LAND                                          77
30 WAREHOUSES                                                      64
21 OFFICE BUILDINGS                                                61
45 CONDO HOTELS                                                    53
26 OTHER HOTELS                                                    49
46 CONDO STORE BUILDINGS                                           44
27 FACTORIES                                                       37
06 TAX CLASS 1 - OTHER                                             32
41 TAX CLASS 4 - OTHER                                             29
16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT                         27
32 HOSPITAL AND HEALTH FACILITIES                                  19
37 RELIGIOUS FACILITIES                                            17
23 LOFT BUILDINGS                                                  15
33 EDUCATIONAL FACILITIES                                          13
28 COMMERCIAL CONDOS                                               11
35 INDOOR PUBLIC AND CULTURAL FACILITIES                            9
11A CONDO-RENTALS                                                   9
25 LUXURY HOTELS                                                    7
48 CONDO TERRACES/GARDENS/CABANAS                                   7
36 OUTDOOR RECREATIONAL FACILITIES                                  6
38 ASYLUMS AND HOMES                                                5
34 THEATRES                                                         2
40 SELECTED GOVERNMENTAL FACILITIES                                 1
49 CONDO WAREHOUSES/FACTORY/INDUS                                   1

In [13]:
#breaking out by borough

bronx_df = real_estate_df.loc[real_estate_df['borough_name'] == 'Bronx']

bronx_bulding_df = pd.DataFrame(bronx_df['building_class_category'].value_counts())

bronx_bulding_df.rename(columns={"Index": "Type of Building"})

bronx_bulding_df

                                              building_class_category
13 CONDOS - ELEVATOR APARTMENTS                                   970
02 TWO FAMILY DWELLINGS                                           891
10 COOPS - ELEVATOR APARTMENTS                                    804
01 ONE FAMILY DWELLINGS                                           641
03 THREE FAMILY DWELLINGS                                         408
07 RENTALS - WALKUP APARTMENTS                                    311
09 COOPS - WALKUP APARTMENTS                                      128
04 TAX CLASS 1 CONDOS                                             127
05 TAX CLASS 1 VACANT LAND                                        110
15 CONDOS - 2-10 UNIT RESIDENTIAL                                 108
44 CONDO PARKING                                                   80
17 CONDO COOPS                                                     78
14 RENTALS - 4-10 UNIT                                             73
22 STORE BUILDINGS                                                 48
47 CONDO NON-BUSINESS STORAGE                                      37
12 CONDOS - WALKUP APARTMENTS                                      36
29 COMMERCIAL GARAGES                                              28
43 CONDO OFFICE BUILDINGS                                          26
08 RENTALS - ELEVATOR APARTMENTS                                   25
30 WAREHOUSES                                                      22
31 COMMERCIAL VACANT LAND                                          21
41 TAX CLASS 4 - OTHER                                             18
46 CONDO STORE BUILDINGS                                           14
21 OFFICE BUILDINGS                                                13
06 TAX CLASS 1 - OTHER                                             11
33 EDUCATIONAL FACILITIES                                          11
37 RELIGIOUS FACILITIES                                            10
16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT                          9
27 FACTORIES                                                        8
26 OTHER HOTELS                                                     7
45 CONDO HOTELS                                                     6
32 HOSPITAL AND HEALTH FACILITIES                                   5
35 INDOOR PUBLIC AND CULTURAL FACILITIES                            4
23 LOFT BUILDINGS                                                   2
48 CONDO TERRACES/GARDENS/CABANAS                                   1
11A CONDO-RENTALS                                                   1
11 SPECIAL CONDO BILLING LOTS                                       1

In [14]:
#breaking out by borough

staten_island_df = real_estate_df.loc[real_estate_df['borough_name'] == 'Staten Island']

staten_island_bulding_df = pd.DataFrame(staten_island_df['building_class_category'].value_counts())

staten_island_bulding_df.rename(columns={"Index": "Type of Building"})

staten_island_bulding_df

                                              building_class_category
13 CONDOS - ELEVATOR APARTMENTS                                  1552
02 TWO FAMILY DWELLINGS                                          1341
10 COOPS - ELEVATOR APARTMENTS                                   1187
01 ONE FAMILY DWELLINGS                                           894
03 THREE FAMILY DWELLINGS                                         431
07 RENTALS - WALKUP APARTMENTS                                    411
09 COOPS - WALKUP APARTMENTS                                      227
44 CONDO PARKING                                                  194
15 CONDOS - 2-10 UNIT RESIDENTIAL                                 136
04 TAX CLASS 1 CONDOS                                             124
05 TAX CLASS 1 VACANT LAND                                        107
12 CONDOS - WALKUP APARTMENTS                                     104
14 RENTALS - 4-10 UNIT                                             87
17 CONDO COOPS                                                     86
22 STORE BUILDINGS                                                 78
29 COMMERCIAL GARAGES                                              62
08 RENTALS - ELEVATOR APARTMENTS                                   53
47 CONDO NON-BUSINESS STORAGE                                      38
31 COMMERCIAL VACANT LAND                                          31
21 OFFICE BUILDINGS                                                28
27 FACTORIES                                                       28
30 WAREHOUSES                                                      28
43 CONDO OFFICE BUILDINGS                                          23
45 CONDO HOTELS                                                    19
26 OTHER HOTELS                                                    18
46 CONDO STORE BUILDINGS                                           15
16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT                         13
41 TAX CLASS 4 - OTHER                                             12
33 EDUCATIONAL FACILITIES                                           9
11A CONDO-RENTALS                                                   9
37 RELIGIOUS FACILITIES                                             9
06 TAX CLASS 1 - OTHER                                              9
23 LOFT BUILDINGS                                                   5
48 CONDO TERRACES/GARDENS/CABANAS                                   5
32 HOSPITAL AND HEALTH FACILITIES                                   4
38 ASYLUMS AND HOMES                                                4
25 LUXURY HOTELS                                                    3
42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC                           2
35 INDOOR PUBLIC AND CULTURAL FACILITIES                            2
28 COMMERCIAL CONDOS                                                2
34 THEATRES                                                         2
36 OUTDOOR RECREATIONAL FACILITIES                                  2
40 SELECTED GOVERNMENTAL FACILITIES                                 1
18 TAX CLASS 3 - UNTILITY PROPERTIES                                1

In [15]:
manhattan_bulding_df.to_csv('data/manhattan_building_class_data.csv', index = True)

In [16]:
queens_bulding_df.to_csv('data/queens_building_class_data.csv', index = True)

In [17]:
bronx_bulding_df.to_csv('data/bronx_building_class_data.csv', index = True)

In [18]:
brooklyn_bulding_df.to_csv('data/brooklyn_building_class_data.csv', index = True)

In [ ]:
queens_bulding_df.to_csv('data/queens_building_class_data.csv', index = True)

In [ ]:
# real_estate_df['']

building_class_count = real_estate_df['building_class_category'].value_counts()

building_class_df = pd.DataFrame(building_class_count)

building_class_df.reset_index()

In [ ]:
building_class_df.to_csv('data/building_class_data.csv', index = True)

In [ ]:
grouped = real_estate_df.groupby(['building_class_category'])

grouped

grouped_df = real_estate_df.groupby(['building_class_category'], as_index=False).agg({'full_address': 'first',
                                                                                     'sale_price': 'mean', 
                                                                                     'neighborhood': 'first', 
                                                                                     'tax_class_at_present': 'first', 
                                                                                     'zip_code': 'first', 
                                                                                     'building_class_at_time_of_sale': 'first', 
                                                                                     'borough_name': 'first',
                                                                                     'latitude': 'first',
                                                                                     'longitude': 'first'})

grouped_df