In [1]:
import pandas as pd
from sqlalchemy import create_engine
from geopy.geocoders import Nominatim

In [2]:
#import csv
real_estate_file = 'data/nyc-rolling-sales.csv'
real_estate_df = pd.read_csv(real_estate_file)


real_estate_df

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,,...,5,0,5,1633,6440,1900,2,C2,6625000,7/19/17 0:00
1,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,,...,28,3,31,4616,18690,1900,2,C7,-,12/14/16 0:00
2,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,,...,16,1,17,2212,7803,1900,2,C7,-,12/9/16 0:00
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,,...,10,0,10,2272,6794,1913,2,C4,3936272,9/23/16 0:00
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,,...,6,0,6,2369,4615,1900,2,C2,8000000,11/17/16 0:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84543,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,34,,B9,37 QUAIL LANE,,...,2,0,2,2400,2575,1998,1,B9,450000,11/28/16 0:00
84544,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,78,,B9,32 PHEASANT LANE,,...,2,0,2,2498,2377,1998,1,B9,550000,4/21/17 0:00
84545,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7351,60,,B2,49 PITNEY AVENUE,,...,2,0,2,4000,1496,1925,1,B2,460000,7/5/17 0:00
84546,5,WOODROW,22 STORE BUILDINGS,4,7100,28,,K6,2730 ARTHUR KILL ROAD,,...,0,7,7,208033,64117,2001,4,K6,11693337,12/21/16 0:00
84547,5,WOODROW,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,7105,679,,P9,155 CLAY PIT ROAD,,...,0,1,1,10796,2400,2006,4,P9,69300,10/27/16 0:00

In [3]:
# change address column type
real_estate_df = real_estate_df.astype({"ADDRESS": object})

real_estate_df.dtypes

BOROUGH                            int64
NEIGHBORHOOD                      object
BUILDING CLASS CATEGORY           object
TAX CLASS AT PRESENT              object
BLOCK                              int64
LOT                                int64
EASE-MENT                         object
BUILDING CLASS AT PRESENT         object
ADDRESS                           object
APARTMENT NUMBER                  object
ZIP CODE                           int64
RESIDENTIAL UNITS                  int64
COMMERCIAL UNITS                   int64
TOTAL UNITS                        int64
LAND SQUARE FEET                  object
GROSS SQUARE FEET                 object
YEAR BUILT                         int64
TAX CLASS AT TIME OF SALE          int64
BUILDING CLASS AT TIME OF SALE    object
SALE PRICE                        object
SALE DATE                         object
dtype: object

In [4]:
#add borough depending on number definfed by the data documentation.
borough_name = []


for b in real_estate_df['BOROUGH']:
    if  b == 1:
        borough_name.append("Manhattan")
        
    elif b == 2:
        borough_name.append("Bronx") 
        
    elif b == 3: 
        borough_name.append("Brooklyn") 
        
    elif b == 4:
        borough_name.append("Queens")
        
    else:
        borough_name.append("Staten Island") 
        

real_estate_df["borough_name"] = borough_name
real_estate_df.sample(50)

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE,borough_name
64771,4,JAMAICA,13 CONDOS - ELEVATOR APARTMENTS,2,9843,1013,,R4,170-12 HIGHLAND AVE,403,...,0,1,-,-,0,2,R4,445000,7/18/17 0:00,Queens
42865,3,OCEAN HILL,02 TWO FAMILY DWELLINGS,1,1493,33,,B1,836 HALSEY STREET,,...,0,2,1800,2430,2016,1,B1,1365000,12/15/16 0:00,Brooklyn
3018,1,FLATIRON,17 CONDO COOPS,2,842,1002,,R9,"69 FIFTH AVENUE, 4G",,...,0,0,-,-,1961,2,R9,1440000,8/1/17 0:00,Manhattan
31981,3,BUSHWICK,13 CONDOS - ELEVATOR APARTMENTS,2,3235,1222,,R4,318 KNICKERBOCKER AVENUE,3K,...,0,1,0,0,1899,2,R4,732250,5/15/17 0:00,Brooklyn
4974,1,HARLEM-CENTRAL,07 RENTALS - WALKUP APARTMENTS,2B,2034,39,,C4,204 WEST 149 STREET,,...,0,10,2498,11226,1920,2,C4,-,4/27/17 0:00,Manhattan
65198,4,KEW GARDENS,02 TWO FAMILY DWELLINGS,1,9249,12,,B2,127-22 KEW GARDENS ROAD,,...,0,2,3805,3760,2014,1,B2,-,1/18/17 0:00,Queens
79602,5,MARINERS HARBOR,01 ONE FAMILY DWELLINGS,1,1224,27,,A5,20 UNION AVENUE,,...,0,1,1708,1150,2001,1,A5,363167,11/17/16 0:00,Staten Island
25718,3,BAY RIDGE,01 ONE FAMILY DWELLINGS,1,6032,1,,A3,8525 COLONIAL ROAD,,...,0,1,4187,1774,1910,1,A3,2100000,4/13/17 0:00,Brooklyn
21943,2,PARKCHESTER,03 THREE FAMILY DWELLINGS,1,4023,1,,C0,1650 MELVILLE STREET,,...,0,3,2375,3105,2003,1,C0,390000,3/6/17 0:00,Bronx
82713,5,SOUTH BEACH,01 ONE FAMILY DWELLINGS,1,3252,57,,A2,289 NORWAY AVENUE,,...,0,1,3000,792,1935,1,A2,10,12/16/16 0:00,Staten Island
16492,1,UPPER WEST SIDE (59-79),47 CONDO NON-BUSINESS STORAGE,4,1171,2330,,RS,240 RIVERSIDE BOULEVARD,SU 62,...,0,1,-,-,2004,4,RS,-,7/13/17 0:00,Manhattan
39075,3,FLATBUSH-NORTH,13 CONDOS - ELEVATOR APARTMENTS,2,4815,1011,,R4,651 NEW YORK AVENUE,303,...,0,1,0,0,2014,2,R4,519307,3/7/17 0:00,Brooklyn
36239,3,EAST NEW YORK,01 ONE FAMILY DWELLINGS,1,4033,36,,A5,468 ELTON ST,,...,0,1,1125,1869,2005,1,A5,390000,9/8/16 0:00,Brooklyn
15187,1,UPPER WEST SIDE (59-79),10 COOPS - ELEVATOR APARTMENTS,2,1119,29,,D4,"65 CENTRAL PARK WEST, 10E",,...,0,0,-,-,1929,2,D4,3800000,5/4/17 0:00,Manhattan
30520,3,BRIGHTON BEACH,15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,8668,1204,,R1,2919 BRIGHTON 8 STREET,2B,...,0,1,0,0,0,2,R1,467000,11/14/16 0:00,Brooklyn
45595,3,PROSPECT HEIGHTS,13 CONDOS - ELEVATOR APARTMENTS,2,1129,1186,,R4,550 VANDERBILT AVENUE,901,...,0,1,0,0,2015,2,R4,2321610,7/21/17 0:00,Brooklyn
43154,3,OCEAN HILL,15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,1503,1103,,R1,729 DECATUR STREET,2B,...,0,1,0,0,2015,2,R1,329550,5/30/17 0:00,Brooklyn
74705,4,SUNNYSIDE,10 COOPS - ELEVATOR APARTMENTS,2,170,1,,D4,"47-37 45TH STREET, 1K",,...,0,0,-,-,1964,2,D4,248000,8/31/17 0:00,Queens
41759,3,MANHATTAN BEACH,44 CONDO PARKING,4,8726,1046,,RG,35 WEST END AVENUE,PS19,...,0,1,0,0,2014,4,RG,0,10/17/16 0:00,Brooklyn
13980,1,UPPER EAST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1525,9,,D4,"215 EAST 79TH STREET, 12EF",,...,0,0,-,-,1947,2,D4,1850000,8/30/17 0:00,Manhattan
21778,2,MOTT HAVEN/PORT MORRIS,37 RELIGIOUS FACILITIES,4,2281,67,,M1,423 EAST 136 STREET,,...,1,1,1667,2250,1910,4,M1,275000,12/14/16 0:00,Bronx
55026,4,ELMHURST,07 RENTALS - WALKUP APARTMENTS,2,1512,6,,C7,87-16 BRITTON AVENUE,,...,1,11,2500,7200,1925,2,C7,2325000,6/20/17 0:00,Queens
66240,4,LONG ISLAND CITY,10 COOPS - ELEVATOR APARTMENTS,2,18,1,,D4,"4-74 48TH AVENUE, 3N",,...,0,0,-,-,1996,2,D4,400000,9/12/16 0:00,Queens
38768,3,FLATBUSH-NORTH,01 ONE FAMILY DWELLINGS,1,4800,22,,A9,664 MAPLE STREET,,...,0,1,1800,1000,1915,1,A9,350000,11/14/16 0:00,Brooklyn
26419,3,BAY RIDGE,15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,5928,1106,,R1,231 BAY RIDGE PARKWAY,3B,...,0,1,0,0,2006,2,R1,960000,10/31/16 0:00,Brooklyn
65382,4,KEW GARDENS,10 COOPS - ELEVATOR APARTMENTS,2,9249,40,,D4,"84-70 129TH STREET, 6B",,...,0,0,-,-,1969,2,D4,240000,2/16/17 0:00,Queens
145,1,ALPHABET CITY,13 CONDOS - ELEVATOR APARTMENTS,2,402,1314,,R4,100 AVENUE A,4C,...,0,1,-,-,2014,2,R4,1385000,12/9/16 0:00,Manhattan
40043,3,GRAVESEND,02 TWO FAMILY DWELLINGS,1,6624,75,,B2,1605 WEST 8TH STREET,,...,0,2,2145,2160,1930,1,B2,1130000,9/26/16 0:00,Brooklyn
49098,3,WILLIAMSBURG-SOUTH,44 CONDO PARKING,4,2129,1742,,RG,26 BROADWAY,PKG10,...,0,1,0,0,2006,4,RG,60000,2/16/17 0:00,Brooklyn
51219,4,BAYSIDE,01 ONE FAMILY DWELLINGS,1,7463,50,,A1,58-19 212TH STREET,,...,0,1,4116,1248,1950,1,A1,808888,12/19/16 0:00,Queens
335,1,CHELSEA,10 COOPS - ELEVATOR APARTMENTS,2,720,47,,D4,"400 WEST 23RD STREET, 2J",,...,0,0,-,-,1920,2,D4,639000,1/19/17 0:00,Manhattan
78886,5,GREAT KILLS,02 TWO FAMILY DWELLINGS,1,5310,49,,B9,76 GLOVER STREET,,...,0,2,2500,1770,1988,1,B9,405000,11/8/16 0:00,Staten Island
76907,5,BULLS HEAD,02 TWO FAMILY DWELLINGS,1,1595,165,,B2,429 HILLMAN AVENUE,,...,0,2,3120,2048,1980,1,B2,630000,6/12/17 0:00,Staten Island
41219,3,KENSINGTON,10 COOPS - ELEVATOR APARTMENTS,2,5339,1,,D4,"207 OCEAN PARKWAY, 2E",,...,0,0,0,0,1963,2,D4,210000,12/22/16 0:00,Brooklyn
35054,3,CYPRESS HILLS,03 THREE FAMILY DWELLINGS,1,3928,44,,C0,106 SHEPHERD AVE,,...,0,3,2000,2048,1910,1,C0,580800,6/21/17 0:00,Brooklyn
61509,4,GLEN OAKS,10 COOPS - ELEVATOR APARTMENTS,2,8489,1,,D4,"27010 GRAND CENTRAL PARKWA, 24D",,...,0,0,-,-,1972,2,D4,-,12/21/16 0:00,Queens
49129,3,WINDSOR TERRACE,01 ONE FAMILY DWELLINGS,1,5268,78,,A5,230 SEELEY STREET,,...,0,1,2550,1970,1905,1,A5,0,1/18/17 0:00,Brooklyn
21425,2,MORRISANIA/LONGWOOD,03 THREE FAMILY DWELLINGS,1,2733,24,,C0,925 BRUCKNER BOULEVARD,,...,0,3,2500,3814,1901,1,C0,280000,3/15/17 0:00,Bronx
78307,5,GREAT KILLS,01 ONE FAMILY DWELLINGS,1,4478,277,,A5,163 COTTER AVENUE,,...,0,1,1484,1099,1986,1,A5,355000,4/28/17 0:00,Staten Island
67593,4,MIDDLE VILLAGE,44 CONDO PARKING,4,3057,1009,,RG,72-29 METROPOLITAN AVENUE,IP8,...,0,1,-,-,1987,4,RG,-,3/30/17 0:00,Queens
20659,2,KINGSBRIDGE/JEROME PARK,10 COOPS - ELEVATOR APARTMENTS,2,3252,209,,D4,"80 VAN CORTLANDT PARK S, A22",,...,0,0,0,0,1930,2,D4,100,12/12/16 0:00,Bronx
60984,4,FOREST HILLS,10 COOPS - ELEVATOR APARTMENTS,2,3341,30,,D4,"114-20 QUEENS BOULEVARD, F9",,...,0,0,-,-,1940,2,D4,362000,6/1/17 0:00,Queens
67274,4,MIDDLE VILLAGE,01 ONE FAMILY DWELLINGS,1,3029,160,,A1,6409 71ST STREET,,...,0,1,5400,1040,1910,1,A1,750000,2/7/17 0:00,Queens
52243,4,BELLE HARBOR,02 TWO FAMILY DWELLINGS,1,16256,1,,B3,4-66 BEACH 134 STREET,,...,0,2,6000,2034,1930,1,B3,840000,5/17/17 0:00,Queens
44777,3,PARK SLOPE,10 COOPS - ELEVATOR APARTMENTS,2,982,62,,D4,"333 4 STREET, 3A",,...,0,0,0,0,1931,2,D4,0,8/3/17 0:00,Brooklyn
66550,4,LONG ISLAND CITY,29 COMMERCIAL GARAGES,4,475,7,,G7,9-03 40TH AVENUE,,...,0,0,2508,-,0,4,G7,1500000,11/30/16 0:00,Queens
78466,5,GREAT KILLS,01 ONE FAMILY DWELLINGS,1,5156,62,,A5,42 NASH COURT,,...,0,1,2550,2101,2011,1,A5,-,10/26/16 0:00,Staten Island
20008,2,EAST TREMONT,02 TWO FAMILY DWELLINGS,1,4007,25,,B2,420 BRONX PARK AVENUE,,...,0,2,2358,3584,1910,1,B2,239026,11/4/16 0:00,Bronx
82912,5,STAPLETON,01 ONE FAMILY DWELLINGS,1,556,158,,A5,33 SUSAN COURT,,...,0,1,1715,900,1998,1,A5,290000,3/31/17 0:00,Staten Island
72549,4,SOUTH JAMAICA,02 TWO FAMILY DWELLINGS,1,10083,2,,B2,107-17 PRINCETON,,...,0,2,2625,2080,1915,1,B2,5000,2/10/17 0:00,Queens

In [5]:
#get rid of appt numbers
real_estate_df['ADDRESS'] = real_estate_df['ADDRESS'].str.split(",", n = 1, expand = True)


real_estate_df.sample(50)

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE,borough_name
4711,1,GREENWICH VILLAGE-WEST,13 CONDOS - ELEVATOR APARTMENTS,2,637,1114,,R4,366 WEST 11TH STREET,3B,...,0,1,-,-,1987,2,R4,-,10/18/16 0:00,Manhattan
51359,4,BAYSIDE,02 TWO FAMILY DWELLINGS,1,6299,110,,B2,4221 214TH PLACE,,...,0,2,1625,2109,1930,1,B2,900000,2/7/17 0:00,Queens
64110,4,JACKSON HEIGHTS,10 COOPS - ELEVATOR APARTMENTS,2,1275,20,,D4,35-36 76TH STREET,,...,0,0,-,-,1940,2,D4,375000,2/17/17 0:00,Queens
65021,4,JAMAICA ESTATES,44 CONDO PARKING,4,9944,1008,,RP,180 WEXFORD TERRACE,P8,...,0,1,-,-,1986,4,RP,-,9/2/16 0:00,Queens
57702,4,FLUSHING-NORTH,10 COOPS - ELEVATOR APARTMENTS,2,5180,15,,D4,42-45 KISSENA BOULEVARD,,...,0,0,-,-,1956,2,D4,-,12/20/16 0:00,Queens
35394,3,DOWNTOWN-FULTON FERRY,43 CONDO OFFICE BUILDINGS,4,55,1301,,RB,185 YORK STREET,M1,...,0,1,0,0,2009,4,RB,392027,10/24/16 0:00,Brooklyn
1309,1,CIVIC CENTER,13 CONDOS - ELEVATOR APARTMENTS,2,175,1310,,R4,90 FRANKLIN STREET,5N,...,0,1,-,-,0,2,R4,3195000,3/28/17 0:00,Manhattan
8862,1,MIDTOWN EAST,45 CONDO HOTELS,4,1319,1370,,RH,205 EAST 45TH STREET,1005,...,0,1,-,-,2002,4,RH,-,1/24/17 0:00,Manhattan
40426,3,GRAVESEND,10 COOPS - ELEVATOR APARTMENTS,2,6919,1,,D4,2475 WEST 16 STREET,,...,0,0,0,0,1963,2,D4,248000,6/13/17 0:00,Brooklyn
52402,4,BELLEROSE,01 ONE FAMILY DWELLINGS,1,8620,38,,A1,85-20 253RD STREET,,...,0,1,4000,1120,1935,1,A1,620000,7/7/17 0:00,Queens
29976,3,BOROUGH PARK,15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,5591,1108,,R1,1023 42ND STREET,2,...,0,1,0,0,2005,2,R1,0,2/3/17 0:00,Brooklyn
64166,4,JACKSON HEIGHTS,10 COOPS - ELEVATOR APARTMENTS,2,1281,65,,D4,35-21 81 STREET,,...,0,0,-,-,1930,2,D4,350688,1/30/17 0:00,Queens
16805,1,UPPER WEST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1216,44,,D4,130 WEST 86TH STREET,,...,0,0,-,-,1926,2,D4,1255000,5/31/17 0:00,Manhattan
73784,4,SPRINGFIELD GARDENS,02 TWO FAMILY DWELLINGS,1,12682,4,,B3,120-05 196TH STREET,,...,0,2,4700,1662,1950,1,B3,216000,2/2/17 0:00,Queens
77025,5,BULLS HEAD,04 TAX CLASS 1 CONDOS,1A,1548,1042,,R3,17 JENNIFER LANE,20B,...,0,1,-,-,1989,1,R3,287000,1/23/17 0:00,Staten Island
80636,5,NEW DORP-BEACH,05 TAX CLASS 1 VACANT LAND,1B,4091,4,,V0,59 MILBANK ROAD,,...,0,0,2400,-,0,1,V0,58040,11/8/16 0:00,Staten Island
79326,5,HUGUENOT,02 TWO FAMILY DWELLINGS,1,6891,72,,B2,805 SINCLAIR AVENUE,,...,0,2,4032,2800,1984,1,B2,90000,7/14/17 0:00,Staten Island
73087,4,SOUTH OZONE PARK,01 ONE FAMILY DWELLINGS,1,11781,318,,A1,130-28 VAN WYCK EXPWY SR W,,...,0,1,3000,1026,1935,1,A1,448000,12/9/16 0:00,Queens
72076,4,SO. JAMAICA-BAISLEY PARK,01 ONE FAMILY DWELLINGS,1,12387,88,,A1,120-61 170TH STREET,,...,0,1,4000,1874,1930,1,A1,-,9/21/16 0:00,Queens
34455,3,CROWN HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,1248,32,,C3,908 STERLING PLACE,,...,0,4,1667,2602,1901,2,C3,0,5/4/17 0:00,Brooklyn
53761,4,CORONA,03 THREE FAMILY DWELLINGS,1,1968,3,,C0,110-16 CORONA AVENUE,,...,0,3,2238,2308,1931,1,C0,-,3/9/17 0:00,Queens
69703,4,REGO PARK,10 COOPS - ELEVATOR APARTMENTS,2,3163,15,,D4,67-30 DARTMOUTH,,...,0,0,-,-,1955,2,D4,146000,3/29/17 0:00,Queens
29857,3,BOROUGH PARK,12 CONDOS - WALKUP APARTMENTS,2,923,1007,,R2,873 42ND STREET,2C,...,0,1,0,0,0,2,R2,457000,12/30/16 0:00,Brooklyn
37815,3,FLATBUSH-EAST,01 ONE FAMILY DWELLINGS,1,4957,25,,A9,1260 ALBANY AVENUE,,...,0,1,2000,1552,1920,1,A9,0,9/16/16 0:00,Brooklyn
31789,3,BUSHWICK,03 THREE FAMILY DWELLINGS,1,3409,56,,C0,75 ELDERT STREET,,...,0,3,2000,3900,1899,1,C0,880000,1/19/17 0:00,Brooklyn
69205,4,QUEENS VILLAGE,22 STORE BUILDINGS,4,10610,39,,K4,217-03 JAMAICA AVENUE,,...,3,5,1670,2668,1931,4,K4,-,12/17/16 0:00,Queens
61159,4,FRESH MEADOWS,01 ONE FAMILY DWELLINGS,1,7167,21,,A1,73-11 179TH STREET,,...,0,1,4000,1426,1935,1,A1,950000,3/22/17 0:00,Queens
56777,4,FLUSHING-NORTH,02 TWO FAMILY DWELLINGS,1,4409,36,,B3,31-10 137TH STREET,,...,0,2,3125,1900,1920,1,B3,-,3/16/17 0:00,Queens
7024,1,LOWER EAST SIDE,36 OUTDOOR RECREATIONAL FACILITIES,4,315,40,,Q1,226 EAST BROADWAY,,...,0,0,6675,-,0,4,Q1,47500000,10/27/16 0:00,Manhattan
81722,5,PORT RICHMOND,02 TWO FAMILY DWELLINGS,1,1039,58,,B9,17 MITCHEL LANE,,...,0,2,2192,1600,2003,1,B9,380000,2/21/17 0:00,Staten Island
36013,3,DYKER HEIGHTS,02 TWO FAMILY DWELLINGS,1,5934,57,,B1,963 BAY RIDGE PARKWAY,,...,0,2,2100,2550,1925,1,B1,0,4/26/17 0:00,Brooklyn
39290,3,FLATLANDS,02 TWO FAMILY DWELLINGS,1,7834,23,,B3,1349 EAST 54TH STREET,,...,0,2,2225,1540,1940,1,B3,0,11/9/16 0:00,Brooklyn
74684,4,SUNNYSIDE,10 COOPS - ELEVATOR APARTMENTS,2,131,36,,D4,41-36 51 ST,,...,0,0,-,-,1930,2,D4,225000,10/13/16 0:00,Queens
60094,4,FOREST HILLS,01 ONE FAMILY DWELLINGS,1,2248,6,,S1,71-31 112TH STREET,,...,1,2,5200,1996,1930,1,S1,-,4/10/17 0:00,Queens
31688,3,BUSHWICK,02 TWO FAMILY DWELLINGS,1,3471,12,,B1,62 DE SALES PLACE,,...,0,2,2000,2000,1905,1,B1,0,3/21/17 0:00,Brooklyn
29693,3,BOROUGH PARK,04 TAX CLASS 1 CONDOS,,5695,1703,,,1042 57TH STREET,,...,0,0,0,0,0,1,R6,982611,6/7/17 0:00,Brooklyn
36373,3,EAST NEW YORK,02 TWO FAMILY DWELLINGS,1,3759,15,,B1,335 BRADFORD STREET,,...,0,2,2000,2080,1930,1,B1,300000,9/27/16 0:00,Brooklyn
33798,3,CONEY ISLAND,10 COOPS - ELEVATOR APARTMENTS,2,7273,25,,D4,2932 WEST 5 STREET,,...,0,0,0,0,1964,2,D4,285000,6/8/17 0:00,Brooklyn
24226,2,THROGS NECK,01 ONE FAMILY DWELLINGS,1,5594,72,,A5,270 HUNTINGTON AVENUE,,...,0,1,1767,1534,1960,1,A5,0,9/12/16 0:00,Bronx
72968,4,SOUTH OZONE PARK,01 ONE FAMILY DWELLINGS,1,11688,22,,A1,116-32 133RD STREET,,...,0,1,2000,990,1930,1,A1,-,6/26/17 0:00,Queens
63945,4,JACKSON HEIGHTS,09 COOPS - WALKUP APARTMENTS,2,1278,14,,C6,35-16 79 STREET,,...,0,0,-,-,1920,2,C6,425000,8/17/17 0:00,Queens
16265,1,UPPER WEST SIDE (59-79),17 CONDO COOPS,2,1158,1007,,R9,142 WEST END AVENUE,,...,0,0,-,-,1963,2,R9,920000,3/21/17 0:00,Manhattan
83807,5,WEST NEW BRIGHTON,02 TWO FAMILY DWELLINGS,1,203,20,,B3,42 DE GROOT PLACE,,...,0,2,3080,1500,1899,1,B3,192660,9/19/16 0:00,Staten Island
65600,4,LAURELTON,01 ONE FAMILY DWELLINGS,1,12937,77,,A1,131-02 228TH STREET,,...,0,1,3200,1645,1935,1,A1,-,10/14/16 0:00,Queens
19287,2,BRONXDALE,02 TWO FAMILY DWELLINGS,1,4639,12,,B1,3316 LURTING AVE,,...,0,2,2200,2398,1945,1,B1,480000,6/21/17 0:00,Bronx
73373,4,SOUTH OZONE PARK,22 STORE BUILDINGS,4,11712,41,,K1,119-12 ROCKAWAY BOULEVARD,,...,1,1,832,1550,2005,4,K1,610000,2/16/17 0:00,Queens
6733,1,LITTLE ITALY,22 STORE BUILDINGS,4,478,34,,K4,164 BOWERY,,...,1,4,2430,9484,1900,4,K4,-,6/6/17 0:00,Manhattan
32494,3,CANARSIE,02 TWO FAMILY DWELLINGS,1,8142,58,,B2,980 EAST 93RD STREET,,...,0,2,2800,1120,1935,1,B2,10000,4/25/17 0:00,Brooklyn
43738,3,OCEAN PARKWAY-NORTH,22 STORE BUILDINGS,4,6634,8,,K7,440 AVENUE P,,...,2,2,4000,8000,1936,4,K7,3200000,4/28/17 0:00,Brooklyn
68254,4,OZONE PARK,02 TWO FAMILY DWELLINGS,1,9036,28,,B9,93-03 97TH AVENUE,,...,0,2,1460,1200,1920,1,B9,515000,3/21/17 0:00,Queens

In [6]:
#making new column with full address

real_estate_df["Full_Address"] = real_estate_df["ADDRESS"] + " "  + real_estate_df["borough_name"]

real_estate_df.head(50)

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,...,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE,borough_name,Full_Address
0,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,,...,5,1633,6440,1900,2,C2,6625000,7/19/17 0:00,Manhattan,153 AVENUE B Manhattan
1,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,,...,31,4616,18690,1900,2,C7,-,12/14/16 0:00,Manhattan,234 EAST 4TH STREET Manhattan
2,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,,...,17,2212,7803,1900,2,C7,-,12/9/16 0:00,Manhattan,197 EAST 3RD STREET Manhattan
3,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,,...,10,2272,6794,1913,2,C4,3936272,9/23/16 0:00,Manhattan,154 EAST 7TH STREET Manhattan
4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,,...,6,2369,4615,1900,2,C2,8000000,11/17/16 0:00,Manhattan,301 EAST 10TH STREET Manhattan
5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,405,16,,C4,516 EAST 12TH STREET,,...,20,2581,9730,1900,2,C4,-,7/20/17 0:00,Manhattan,516 EAST 12TH STREET Manhattan
6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,406,32,,C4,210 AVENUE B,,...,8,1750,4226,1920,2,C4,3192840,9/23/16 0:00,Manhattan,210 AVENUE B Manhattan
7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,407,18,,C7,520 EAST 14TH STREET,,...,46,5163,21007,1900,2,C7,-,7/20/17 0:00,Manhattan,520 EAST 14TH STREET Manhattan
8,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,379,34,,D5,141 AVENUE D,,...,15,1534,9198,1920,2,D5,-,6/20/17 0:00,Manhattan,141 AVENUE D Manhattan
9,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,387,153,,D9,629 EAST 5TH STREET,,...,24,4489,18523,1920,2,D9,16232000,11/7/16 0:00,Manhattan,629 EAST 5TH STREET Manhattan
10,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,394,44,,D7,181 AVENUE C,,...,34,4295,21328,1910,2,D7,-,7/20/17 0:00,Manhattan,181 AVENUE C Manhattan
11,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2B,400,21,,D1,530-532 EAST 5TH STREET,,...,10,3717,12350,2009,2,D1,10350000,10/17/16 0:00,Manhattan,530-532 EAST 5TH STREET Manhattan
12,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,40,,C6,327 EAST 3RD STREET,,...,0,-,-,1920,2,C6,1,9/6/16 0:00,Manhattan,327 EAST 3RD STREET Manhattan
13,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,40,,C6,327 EAST 3RD STREET,,...,0,-,-,1920,2,C6,499000,3/10/17 0:00,Manhattan,327 EAST 3RD STREET Manhattan
14,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,40,,C6,327 EAST 3RD STREET,,...,0,-,-,1920,2,C6,10,4/28/17 0:00,Manhattan,327 EAST 3RD STREET Manhattan
15,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,40,,C6,327 EAST 3RD STREET,,...,0,-,-,1920,2,C6,529500,6/9/17 0:00,Manhattan,327 EAST 3RD STREET Manhattan
16,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,40,,C6,327 EAST 3RD STREET,,...,0,-,-,1920,2,C6,423000,7/14/17 0:00,Manhattan,327 EAST 3RD STREET Manhattan
17,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,46,,C6,317 EAST 3RD STREET,,...,0,-,-,1925,2,C6,501000,3/16/17 0:00,Manhattan,317 EAST 3RD STREET Manhattan
18,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,49,,C6,311 EAST 3RD STREET,,...,0,-,-,1920,2,C6,450000,9/1/16 0:00,Manhattan,311 EAST 3RD STREET Manhattan
19,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,49,,C6,311 EAST 3RD,,...,0,-,-,1920,2,C6,510000,8/17/17 0:00,Manhattan,311 EAST 3RD Manhattan
20,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,374,8,,C6,702 EAST 5TH STREET,,...,0,-,-,1900,2,C6,-,9/7/16 0:00,Manhattan,702 EAST 5TH STREET Manhattan
21,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,375,30,,C6,742 EAST 6TH STREET,,...,0,-,-,1902,2,C6,350000,8/30/17 0:00,Manhattan,742 EAST 6TH STREET Manhattan
22,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,14,,C6,244 EAST 7TH STREET,,...,24,4131,16776,1928,2,C6,11900000,6/21/17 0:00,Manhattan,244 EAST 7TH STREET Manhattan
23,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,14,,C6,244 EAST 7TH STREET,,...,0,-,-,1928,2,C6,11900000,6/21/17 0:00,Manhattan,244 EAST 7TH STREET Manhattan
24,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,16,,C6,248 EAST 7TH STREET,,...,0,-,-,1928,2,C6,350000,1/30/17 0:00,Manhattan,248 EAST 7TH STREET Manhattan
25,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,16,,C6,248 EAST 7TH STREET,,...,0,-,-,1928,2,C6,404000,7/7/17 0:00,Manhattan,248 EAST 7TH STREET Manhattan
26,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,19,,C6,254 EAST 7TH STREET,,...,0,-,-,1910,2,C6,535000,6/21/17 0:00,Manhattan,254 EAST 7TH STREET Manhattan
27,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,377,54,,C6,267 EAST 7TH ST,,...,0,-,-,1920,2,C6,1400000,8/4/17 0:00,Manhattan,267 EAST 7TH ST Manhattan
28,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,377,60,,C6,255 EAST 7TH STREET,,...,0,-,-,1900,2,C6,866000,1/9/17 0:00,Manhattan,255 EAST 7TH STREET Manhattan
29,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,379,15,,C6,414 EAST 10TH STREET,,...,0,-,-,1930,2,C6,355000,4/18/17 0:00,Manhattan,414 EAST 10TH STREET Manhattan
30,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,379,15,,C6,414 EAST 10TH STREET,,...,0,-,-,1930,2,C6,-,6/19/17 0:00,Manhattan,414 EAST 10TH STREET Manhattan
31,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,389,21,,C6,206 EAST 7TH STREET,,...,0,-,-,1900,2,C6,805000,8/28/17 0:00,Manhattan,206 EAST 7TH STREET Manhattan
32,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,389,49,,C6,623 EAST 6TH STREET,,...,0,-,-,1910,2,C6,475000,5/10/17 0:00,Manhattan,623 EAST 6TH STREET Manhattan
33,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,389,50,,C6,621 EAST 6TH STREET,,...,0,-,-,1920,2,C6,450000,12/2/16 0:00,Manhattan,621 EAST 6TH STREET Manhattan
34,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,389,50,,C6,621 EAST 6TH STREET,,...,0,-,-,1920,2,C6,450000,1/31/17 0:00,Manhattan,621 EAST 6TH STREET Manhattan
35,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,390,55,,C6,199 EAST 7TH STREET,,...,0,-,-,1935,2,C6,810000,6/28/17 0:00,Manhattan,199 EAST 7TH STREET Manhattan
36,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,391,14,,C6,616 EAST 9TH STREET,,...,0,-,-,1910,2,C6,-,12/7/16 0:00,Manhattan,616 EAST 9TH STREET Manhattan
37,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,391,14,,C6,618 EAST 9TH STREET,,...,0,-,-,1910,2,C6,300000,8/24/17 0:00,Manhattan,618 EAST 9TH STREET Manhattan
38,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,391,14,,C6,620 EAST 9TH STREET,,...,0,-,-,1910,2,C6,300000,8/30/17 0:00,Manhattan,620 EAST 9TH STREET Manhattan
39,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,391,48,,C6,323 EAST 8TH STREET,,...,0,-,-,1910,2,C6,579000,6/27/17 0:00,Manhattan,323 EAST 8TH STREET Manhattan
40,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,391,57,,C6,303 EAST 8TH STREET,,...,0,-,-,1900,2,C6,1500000,3/17/17 0:00,Manhattan,303 EAST 8TH STREET Manhattan
41,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,393,39,,C6,163 AVENUE C,,...,0,-,-,1900,2,C6,25000,6/14/17 0:00,Manhattan,163 AVENUE C Manhattan
42,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,394,52,,C6,633 EAST 11TH STREET,,...,0,-,-,1937,2,C6,512000,1/17/17 0:00,Manhattan,633 EAST 11TH STREET Manhattan
43,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,394,52,,C6,633 EAST 11TH STREET,,...,0,-,-,1937,2,C6,410000,1/11/17 0:00,Manhattan,633 EAST 11TH STREET Manhattan
44,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,394,52,,C6,633 EAST 11TH STREET,,...,0,-,-,1937,2,C6,500000,4/21/17 0:00,Manhattan,633 EAST 11TH STREET Manhattan
45,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,394,52,,C6,633 E 11TH ST,,...,0,-,-,1937,2,C6,510000,6/29/17 0:00,Manhattan,633 E 11TH ST Manhattan
46,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,396,20,,C6,634 EAST 14TH STREET,,...,0,-,-,1920,2,C6,475000,10/5/16 0:00,Manhattan,634 EAST 14TH STREET Manhattan
47,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,396,20,,C6,634 EAST 14TH STREET,,...,0,-,-,1920,2,C6,789019,2/2/17 0:00,Manhattan,634 EAST 14TH STREET Manhattan
48,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,396,20,,C6,626 EAST 14TH STREET,,...,0,-,-,1920,2,C6,-,3/20/17 0:00,Manhattan,626 EAST 14TH STREET Manhattan
49,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,396,20,,C6,632 EAST 14TH STREET,,...,0,-,-,1920,2,C6,-,3/20/17 0:00,Manhattan,632 EAST 14TH STREET Manhattan

In [7]:
#picking columns and assigning to new dataframe
real_estate_cols = ['Full_Address','NEIGHBORHOOD', 'TAX CLASS AT PRESENT',
                   'ZIP CODE', 'SALE PRICE', 'BUILDING CLASS AT TIME OF SALE', 'borough_name', 'Full_Address']

real_estate_clean_df = real_estate_df[real_estate_cols]

real_estate_clean_df.reset_index(drop=True)

real_estate_clean_df

,Full_Address,NEIGHBORHOOD,TAX CLASS AT PRESENT,ZIP CODE,SALE PRICE,BUILDING CLASS AT TIME OF SALE,borough_name,Full_Address
0,153 AVENUE B Manhattan,ALPHABET CITY,2A,10009,6625000,C2,Manhattan,153 AVENUE B Manhattan
1,234 EAST 4TH STREET Manhattan,ALPHABET CITY,2,10009,-,C7,Manhattan,234 EAST 4TH STREET Manhattan
2,197 EAST 3RD STREET Manhattan,ALPHABET CITY,2,10009,-,C7,Manhattan,197 EAST 3RD STREET Manhattan
3,154 EAST 7TH STREET Manhattan,ALPHABET CITY,2B,10009,3936272,C4,Manhattan,154 EAST 7TH STREET Manhattan
4,301 EAST 10TH STREET Manhattan,ALPHABET CITY,2A,10009,8000000,C2,Manhattan,301 EAST 10TH STREET Manhattan
...,...,...,...,...,...,...,...,...
84543,37 QUAIL LANE Staten Island,WOODROW,1,10309,450000,B9,Staten Island,37 QUAIL LANE Staten Island
84544,32 PHEASANT LANE Staten Island,WOODROW,1,10309,550000,B9,Staten Island,32 PHEASANT LANE Staten Island
84545,49 PITNEY AVENUE Staten Island,WOODROW,1,10309,460000,B2,Staten Island,49 PITNEY AVENUE Staten Island
84546,2730 ARTHUR KILL ROAD Staten Island,WOODROW,4,10309,11693337,K6,Staten Island,2730 ARTHUR KILL ROAD Staten Island
84547,155 CLAY PIT ROAD Staten Island,WOODROW,4,10309,69300,P9,Staten Island,155 CLAY PIT ROAD Staten Island

In [8]:
#dropping duplicates 
real_estate_dup_drops = real_estate_clean_df.drop_duplicates(subset=['Full_Address'])

real_estate_dup_drops.reset_index(drop = True)

real_estate_dup_drops

,Full_Address,NEIGHBORHOOD,TAX CLASS AT PRESENT,ZIP CODE,SALE PRICE,BUILDING CLASS AT TIME OF SALE,borough_name,Full_Address
0,153 AVENUE B Manhattan,ALPHABET CITY,2A,10009,6625000,C2,Manhattan,153 AVENUE B Manhattan
1,234 EAST 4TH STREET Manhattan,ALPHABET CITY,2,10009,-,C7,Manhattan,234 EAST 4TH STREET Manhattan
2,197 EAST 3RD STREET Manhattan,ALPHABET CITY,2,10009,-,C7,Manhattan,197 EAST 3RD STREET Manhattan
3,154 EAST 7TH STREET Manhattan,ALPHABET CITY,2B,10009,3936272,C4,Manhattan,154 EAST 7TH STREET Manhattan
4,301 EAST 10TH STREET Manhattan,ALPHABET CITY,2A,10009,8000000,C2,Manhattan,301 EAST 10TH STREET Manhattan
...,...,...,...,...,...,...,...,...
84543,37 QUAIL LANE Staten Island,WOODROW,1,10309,450000,B9,Staten Island,37 QUAIL LANE Staten Island
84544,32 PHEASANT LANE Staten Island,WOODROW,1,10309,550000,B9,Staten Island,32 PHEASANT LANE Staten Island
84545,49 PITNEY AVENUE Staten Island,WOODROW,1,10309,460000,B2,Staten Island,49 PITNEY AVENUE Staten Island
84546,2730 ARTHUR KILL ROAD Staten Island,WOODROW,4,10309,11693337,K6,Staten Island,2730 ARTHUR KILL ROAD Staten Island
84547,155 CLAY PIT ROAD Staten Island,WOODROW,4,10309,69300,P9,Staten Island,155 CLAY PIT ROAD Staten Island

In [9]:
#create lat and long columns 

geolocator = Nominatim(user_agent="user_agent")
location = geolocator.geocode("327 EAST 3rd STREET Manhattan")

print((location.latitude, location.longitude))

(40.7208628, -73.9784408)

In [10]:
lat = []
long = []

geolocator = Nominatim(user_agent="user_agent")

for address in real_estate_dup_drops["Full_Address"]:
    
    addr = geolocator.geocode(address, timeout=10)  
    
#     try: 
#         latitude = addr.latitude
#         lat.append(latitude)
#     except:
        
#         pass
    
    if addr is None:
        lat.append(None)
        long.append(None)
        
    else:
        latitude = addr.latitude
        longitude = addr.longitude  
    
        lat.append(latitude)
        long.append(longitude)

real_estate_dup_drops['latitude'] = lat
real_estate_df['longitude'] = long

ValueError: Length of values does not match length of index

In [ ]:
real_estate_dup_drops

In [ ]:
# #import requests to get lat long for each address
# import requests

# response = requests.get('https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA')

# resp_json_payload = response.json()

# print(resp_json_payload['results'][0]['geometry']['location'])