In [1]:
import pandas as pd
from sqlalchemy import create_engine
from geopy.geocoders import Nominatim

In [2]:
#import csv
real_estate_file = 'data/nyc-rolling-sales.csv'
real_estate_df = pd.read_csv(real_estate_file)
real_estate_df

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,...,5,0,5,1633,6440,1900,2,C2,6625000,7/19/17 0:00
1,5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,...,28,3,31,4616,18690,1900,2,C7,-,12/14/16 0:00
2,6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,...,16,1,17,2212,7803,1900,2,C7,-,12/9/16 0:00
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,...,10,0,10,2272,6794,1913,2,C4,3936272,9/23/16 0:00
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,...,6,0,6,2369,4615,1900,2,C2,8000000,11/17/16 0:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84543,8409,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,34,,B9,37 QUAIL LANE,...,2,0,2,2400,2575,1998,1,B9,450000,11/28/16 0:00
84544,8410,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,78,,B9,32 PHEASANT LANE,...,2,0,2,2498,2377,1998,1,B9,550000,4/21/17 0:00
84545,8411,5,WOODROW,02 TWO FAMILY DWELLINGS,1,7351,60,,B2,49 PITNEY AVENUE,...,2,0,2,4000,1496,1925,1,B2,460000,7/5/17 0:00
84546,8412,5,WOODROW,22 STORE BUILDINGS,4,7100,28,,K6,2730 ARTHUR KILL ROAD,...,0,7,7,208033,64117,2001,4,K6,11693337,12/21/16 0:00
84547,8413,5,WOODROW,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,7105,679,,P9,155 CLAY PIT ROAD,...,0,1,1,10796,2400,2006,4,P9,69300,10/27/16 0:00

In [3]:
borough_name = []


for b in real_estate_df['BOROUGH']:
    if  b == 1:
        borough_name.append("Manhattan")
        
    elif b == 2:
        borough_name.append("Bronx") 
        
    elif b == 3: 
        borough_name.append("Brooklyn") 
        
    elif b == 4:
        borough_name.append("Queens")
        
    else:
        borough_name.append("Staten Island") 
        

real_estate_df["borough_name"] = borough_name
real_estate_df.sample(50)

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE,borough_name
34266,8915,3,CROWN HEIGHTS,02 TWO FAMILY DWELLINGS,1,1384,2,,S2,251 SCHENECTADY AVENUE,...,1,3,1368,3135,1925,1,S2,999990,7/5/17 0:00,Brooklyn
72556,23158,4,SOUTH JAMAICA,02 TWO FAMILY DWELLINGS,1,10088,29,,B2,146-47 107TH AVENUE,...,0,2,2500,2151,1920,1,B2,-,7/21/17 0:00,Queens
66883,17485,4,MASPETH,02 TWO FAMILY DWELLINGS,1,2641,55,,B2,60-88 56TH STREET,...,0,2,2000,1720,1920,1,B2,840000,12/23/16 0:00,Queens
31336,5985,3,BUSH TERMINAL,13 CONDOS - ELEVATOR APARTMENTS,2,821,1006,,R4,5418 3RD AVENUE,...,0,1,0,0,2012,2,R4,480000,2/23/17 0:00,Brooklyn
5976,5980,1,HARLEM-EAST,31 COMMERCIAL VACANT LAND,4,1674,51,,V1,N/A 2 AVENUE,...,0,0,2500,-,0,4,V1,-,12/29/16 0:00,Manhattan
83296,7162,5,TOTTENVILLE,01 ONE FAMILY DWELLINGS,1,7867,50,,A1,146 SPRAGUE AVENUE,...,0,1,20000,1616,1920,1,A1,865000,6/30/17 0:00,Staten Island
75629,26231,4,WOODHAVEN,02 TWO FAMILY DWELLINGS,1,9179,8,,B1,85-26 102ND STREET,...,0,2,3060,2088,1910,1,B1,25000,9/15/16 0:00,Queens
79491,3357,5,MANOR HEIGHTS,02 TWO FAMILY DWELLINGS,1,802,102,,B9,129 MONROE,...,0,2,4000,1520,1970,1,B9,-,6/17/17 0:00,Staten Island
34022,8671,3,CROWN HEIGHTS,01 ONE FAMILY DWELLINGS,1,1291,18,,A9,1274 CARROLL STREET,...,0,1,2555,2628,1905,1,A9,0,1/23/17 0:00,Brooklyn
47704,22353,3,WILLIAMSBURG-CENTRAL,13 CONDOS - ELEVATOR APARTMENTS,2,2261,1026,,R4,KENT AVENUE,...,0,1,0,0,0,2,R4,865512,6/5/17 0:00,Brooklyn
71416,22018,4,ROSEDALE,01 ONE FAMILY DWELLINGS,1,13659,28,,A1,149-78 WELLER LANE,...,0,1,2500,1248,1965,1,A1,-,3/11/17 0:00,Queens
46420,21069,3,SHEEPSHEAD BAY,10 COOPS - ELEVATOR APARTMENTS,2,7456,6,,D4,"2626 HOMECREST AVENUE, 6T",...,0,0,0,0,1958,2,D4,429000,9/1/16 0:00,Brooklyn
237,241,1,CHELSEA,08 RENTALS - ELEVATOR APARTMENTS,2,700,44,,D6,516 WEST 29TH STREET,...,1,211,2468,269584,2014,2,D6,-,5/25/17 0:00,Manhattan
64255,14857,4,JACKSON HEIGHTS,10 COOPS - ELEVATOR APARTMENTS,2,1438,1,,D4,"33-44 91 STREET, 3M",...,0,0,-,-,1957,2,D4,185000,3/16/17 0:00,Queens
13448,13452,1,UPPER EAST SIDE (79-96),02 TWO FAMILY DWELLINGS,1,1510,9,,B3,113 EAST 81ST STREET,...,0,2,2043,4000,1899,1,B3,-,10/12/16 0:00,Manhattan
58533,9135,4,FLUSHING-NORTH,13 CONDOS - ELEVATOR APARTMENTS,2,5066,2084,,R4,131-03 40TH ROAD,...,0,1,-,-,2016,2,R4,731854,7/25/17 0:00,Queens
22485,4183,2,PELHAM PARKWAY NORTH,02 TWO FAMILY DWELLINGS,1,4379,8,,B3,1325 PELHAM PARKWAY NORTH,...,0,2,3500,1856,1950,1,B3,800000,2/17/17 0:00,Bronx
10679,10683,1,SOHO,10 COOPS - ELEVATOR APARTMENTS,2,516,7,,D0,"140 THOMPSON STREET, 2D",...,0,0,-,-,1903,2,D0,-,4/19/17 0:00,Manhattan
64182,14784,4,JACKSON HEIGHTS,10 COOPS - ELEVATOR APARTMENTS,2,1291,64,,D4,"37-21 80 STREET, 2I",...,0,0,-,-,1928,2,D4,196310,9/29/16 0:00,Queens
68265,18867,4,OZONE PARK,02 TWO FAMILY DWELLINGS,1,9046,54,,B2,97-17 DREW STREET,...,0,2,2829,2082,1940,1,B2,763000,8/25/17 0:00,Queens
39218,13867,3,FLATLANDS,02 TWO FAMILY DWELLINGS,1,7738,20,,B1,987 EAST 54TH STREET,...,0,2,2200,1914,1960,1,B1,0,11/14/16 0:00,Brooklyn
7496,7500,1,MIDTOWN EAST,07 RENTALS - WALKUP APARTMENTS,2B,1369,34,,C4,430 EAST 58TH STREET,...,0,9,1933,7260,1900,2,C4,-,3/16/17 0:00,Manhattan
14925,14929,1,UPPER EAST SIDE (79-96),13 CONDOS - ELEVATOR APARTMENTS,2,1584,1073,,R4,170 EAST END AVENUE,...,0,1,-,-,2005,2,R4,9237500,5/9/17 0:00,Manhattan
81946,5812,5,PRINCES BAY,02 TWO FAMILY DWELLINGS,1,6672,52,,B9,36 SEGUINE LOOP,...,0,2,2500,1768,1999,1,B9,599000,7/24/17 0:00,Staten Island
37307,11956,3,FLATBUSH-CENTRAL,02 TWO FAMILY DWELLINGS,1,5128,13,,B2,102 VERONICA PLACE,...,0,2,1999,1600,1920,1,B2,600000,8/11/17 0:00,Brooklyn
19777,1475,2,COUNTRY CLUB,01 ONE FAMILY DWELLINGS,1,5460,4,,A5,3210 LAYTON,...,0,1,1452,1728,1955,1,A5,452400,5/26/17 0:00,Bronx
83936,7802,5,WESTERLEIGH,01 ONE FAMILY DWELLINGS,1,407,3,,A2,145 GARRISON AVENUE,...,0,1,2590,1008,1950,1,A2,360000,3/10/17 0:00,Staten Island
14688,14692,1,UPPER EAST SIDE (79-96),13 CONDOS - ELEVATOR APARTMENTS,2,1543,1060,,R4,345 EAST 80TH STREET,...,0,1,-,-,1973,2,R4,-,9/7/16 0:00,Manhattan
37148,11797,3,EAST NEW YORK,31 COMMERCIAL VACANT LAND,4,4368,35,,V1,103 WORTMAN AVENUE,...,0,0,1900,0,0,4,V1,0,7/2/17 0:00,Brooklyn
53194,3796,4,COLLEGE POINT,02 TWO FAMILY DWELLINGS,1,4129,27,,B1,18-18 124TH STREET,...,0,2,2500,2040,2000,1,B1,1200000,8/16/17 0:00,Queens
76081,26683,4,WOODSIDE,22 STORE BUILDINGS,4,1195,31,,K2,34-27 56TH STREET,...,1,1,8200,2970,1928,4,K2,2800000,6/28/17 0:00,Queens
50578,1180,4,ASTORIA,17 CONDO COOPS,2,830,1002,,R9,"2138 35 STREET, 2F",...,0,0,-,-,1932,2,R9,310000,10/10/16 0:00,Queens
60777,11379,4,FOREST HILLS,10 COOPS - ELEVATOR APARTMENTS,2,2248,74,,D4,"112-15 72ND RD, 105",...,0,0,-,-,1940,2,D4,368500,4/5/17 0:00,Queens
20184,1882,2,FORDHAM,05 TAX CLASS 1 VACANT LAND,1B,3156,61,,V0,2069 RYER AVE,...,0,0,2711,0,0,1,V0,550000,7/17/17 0:00,Bronx
33656,8305,3,COBBLE HILL-WEST,04 TAX CLASS 1 CONDOS,1A,347,1061,,R3,55 CARROLL STREET,...,0,1,0,0,0,1,R3,785000,9/21/16 0:00,Brooklyn
81487,5353,5,PLEASANT PLAINS,02 TWO FAMILY DWELLINGS,1,6775,241,,B2,32 SHERWOOD AVENUE,...,0,2,9482,2170,1996,1,B2,-,5/11/17 0:00,Staten Island
61971,12573,4,GLENDALE,07 RENTALS - WALKUP APARTMENTS,2A,3695,34,,C3,72-41 MYRTLE AVENUE,...,0,4,2770,3040,1931,2,C3,-,6/13/17 0:00,Queens
69490,20092,4,REGO PARK,10 COOPS - ELEVATOR APARTMENTS,2,2093,1,,D4,"61-35 98 STREET, 11J",...,0,0,-,-,1960,2,D4,530000,1/11/17 0:00,Queens
26786,1435,3,BEDFORD STUYVESANT,02 TWO FAMILY DWELLINGS,1,1768,18,,B1,604 WILLOUGHBY AVENUE,...,0,2,1733,2079,1910,1,B1,210,3/7/17 0:00,Brooklyn
65024,15626,4,JAMAICA HILLS,01 ONE FAMILY DWELLINGS,1,6717,124,,A5,150-17 COOLIDGE AVENUE,...,0,1,2300,1280,1920,1,A5,-,11/29/16 0:00,Queens
8246,8250,1,MIDTOWN EAST,13 CONDOS - ELEVATOR APARTMENTS,2,1320,1152,,R4,240 EAST 47TH STREET,...,0,1,-,-,1982,2,R4,2160000,4/4/17 0:00,Manhattan
37992,12641,3,FLATBUSH-EAST,01 ONE FAMILY DWELLINGS,1,7745,4,,A1,4113 AVENUE I,...,0,1,2438,1296,1940,1,A1,445000,10/19/16 0:00,Brooklyn
53958,4560,4,CORONA,10 COOPS - ELEVATOR APARTMENTS,2,1964,1,,D4,"59-30 108TH STREET, 7II",...,0,0,-,-,1965,2,D4,325000,4/13/17 0:00,Queens
26484,1133,3,BEDFORD STUYVESANT,01 ONE FAMILY DWELLINGS,1,1704,6,,S1,1876A FULTON STREET,...,1,2,2000,1920,1925,1,S1,1100000,6/15/17 0:00,Brooklyn
21037,2735,2,MORRIS PARK/VAN NEST,01 ONE FAMILY DWELLINGS,1,4107,16,,S1,1659 WILLIAMSBRIDGE ROAD,...,1,2,2275,1676,1925,1,S1,430000,1/30/17 0:00,Bronx
33799,8448,3,CONEY ISLAND,10 COOPS - ELEVATOR APARTMENTS,2,7273,25,,D4,"2928 WEST 5TH STREET, 2E",...,0,0,0,0,1964,2,D4,330000,6/15/17 0:00,Brooklyn
2254,2258,1,FINANCIAL,13 CONDOS - ELEVATOR APARTMENTS,2,18,1093,,R4,88 GREENWICH ST,...,0,1,-,-,1956,2,R4,712000,4/17/17 0:00,Manhattan
26788,1437,3,BEDFORD STUYVESANT,02 TWO FAMILY DWELLINGS,1,1770,81,,B2,33 PULASKI STREET,...,0,2,1875,2139,1915,1,B2,900000,5/4/17 0:00,Brooklyn
16834,16838,1,UPPER WEST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1224,1,,D4,"175 WEST 93RD STREET, 16B",...,0,0,-,-,1929,2,D4,840000,8/31/17 0:00,Manhattan
60879,11481,4,FOREST HILLS,10 COOPS - ELEVATOR APARTMENTS,2,3236,35,,D4,"70-25 YELLOWSTONE BLVD, 18Y",...,0,0,-,-,1965,2,D4,395000,1/11/17 0:00,Queens

In [4]:
# change address column type
real_estate_df = real_estate_df.astype({"ADDRESS": object})

real_estate_df.dtypes

Unnamed: 0                         int64
BOROUGH                            int64
NEIGHBORHOOD                      object
BUILDING CLASS CATEGORY           object
TAX CLASS AT PRESENT              object
BLOCK                              int64
LOT                                int64
EASE-MENT                         object
BUILDING CLASS AT PRESENT         object
ADDRESS                           object
APARTMENT NUMBER                  object
ZIP CODE                           int64
RESIDENTIAL UNITS                  int64
COMMERCIAL UNITS                   int64
TOTAL UNITS                        int64
LAND SQUARE FEET                  object
GROSS SQUARE FEET                 object
YEAR BUILT                         int64
TAX CLASS AT TIME OF SALE          int64
BUILDING CLASS AT TIME OF SALE    object
SALE PRICE                        object
SALE DATE                         object
borough_name                      object
dtype: object

In [5]:
#get rid of appt numbers
real_estate_df['ADDRESS'] = real_estate_df['ADDRESS'].str.split(",", n = 1, expand = True)


real_estate_df.sample(50)

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE,borough_name
83575,7441,5,TRAVIS,30 WAREHOUSES,4,2661,11,,E1,4380 VICTORY BOULEVARD,...,1,1,5304,3100,1899,4,E1,600000,6/14/17 0:00,Staten Island
79298,3164,5,HUGUENOT,02 TWO FAMILY DWELLINGS,1,6338,88,,B2,610 SHELDON AVENUE,...,0,2,4000,-,2016,1,B2,475000,4/17/17 0:00,Staten Island
45498,20147,3,PROSPECT HEIGHTS,13 CONDOS - ELEVATOR APARTMENTS,2,1129,1027,,R4,550 VANDERBILT AVENUE,...,0,1,0,0,2015,2,R4,893000,6/6/17 0:00,Brooklyn
76975,841,5,BULLS HEAD,02 TWO FAMILY DWELLINGS,1,2154,44,,B2,96 AMSTERDAM AVENUE,...,0,2,4600,2004,1970,1,B2,549855,7/24/17 0:00,Staten Island
7633,7637,1,MIDTOWN EAST,10 COOPS - ELEVATOR APARTMENTS,2,1333,1,,D4,305 EAST 40TH STREET,...,0,0,-,-,1963,2,D4,407500,1/30/17 0:00,Manhattan
58665,9267,4,FLUSHING-NORTH,13 CONDOS - ELEVATOR APARTMENTS,2,5135,1029,,R4,136-24 MAPLE AVENUE,...,0,1,-,-,1984,2,R4,815000,4/7/17 0:00,Queens
77721,1587,5,ELTINGVILLE,01 ONE FAMILY DWELLINGS,1,5420,90,,A5,116 MAYBERRY PROMENADE,...,0,1,2070,1260,1975,1,A5,-,5/19/17 0:00,Staten Island
70473,21075,4,RICHMOND HILL,02 TWO FAMILY DWELLINGS,1,9529,43,,B3,106-03 107TH AVENUE,...,0,2,1900,1280,1920,1,B3,-,6/2/17 0:00,Queens
41384,16033,3,MADISON,01 ONE FAMILY DWELLINGS,1,7333,71,,A5,2043 EAST 28TH STREET,...,0,1,1775,1785,1930,1,A5,0,10/6/16 0:00,Brooklyn
8278,8282,1,MIDTOWN EAST,13 CONDOS - ELEVATOR APARTMENTS,2,1320,2087,,R4,236 EAST 47TH STREET,...,0,1,-,-,1988,2,R4,805000,12/22/16 0:00,Manhattan
34455,9104,3,CROWN HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,1248,32,,C3,908 STERLING PLACE,...,0,4,1667,2602,1901,2,C3,0,5/4/17 0:00,Brooklyn
32330,6979,3,CANARSIE,02 TWO FAMILY DWELLINGS,1,7967,73,,B2,580 EAST 89TH STREET,...,0,2,1852,1184,1910,1,B2,0,9/9/16 0:00,Brooklyn
69575,20177,4,REGO PARK,10 COOPS - ELEVATOR APARTMENTS,2,2112,1,,D4,63-61 99TH STREET,...,0,0,-,-,1947,2,D4,450000,11/1/16 0:00,Queens
79190,3056,5,GRYMES HILL,13 CONDOS - ELEVATOR APARTMENTS,2,631,1021,,R4,755 NARROWS ROAD NORTH,...,0,1,-,-,1987,2,R4,235000,6/2/17 0:00,Staten Island
31088,5737,3,BROWNSVILLE,01 ONE FAMILY DWELLINGS,1,3552,46,,A5,192 LEGION STREET,...,0,1,1800,1148,1986,1,A5,185000,3/23/17 0:00,Brooklyn
78124,1990,5,GRANT CITY,13 CONDOS - ELEVATOR APARTMENTS,2,3543,1059,,R4,175 ZOE STREET,...,0,1,-,-,1986,2,R4,225000,12/21/16 0:00,Staten Island
4737,4741,1,GREENWICH VILLAGE-WEST,15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,624,1408,,R1,607 HUDSON STREET,...,0,1,-,-,1906,2,R1,-,1/24/17 0:00,Manhattan
50519,1121,4,ASTORIA,13 CONDOS - ELEVATOR APARTMENTS,2,881,1017,,R4,23-11 21ST AVENUE,...,0,1,-,-,2008,2,R4,770000,11/22/16 0:00,Queens
76924,790,5,BULLS HEAD,02 TWO FAMILY DWELLINGS,1,1632,109,,B9,118 FAHY AVENUE,...,0,2,3150,2592,1987,1,B9,-,5/3/17 0:00,Staten Island
76177,43,5,ANNADALE,01 ONE FAMILY DWELLINGS,1,6242,28,,A5,48 MOSELY AVENUE,...,0,1,4070,1200,1975,1,A5,100000,4/5/17 0:00,Staten Island
45358,20007,3,PROSPECT HEIGHTS,09 COOPS - WALKUP APARTMENTS,2C,1158,67,,C6,207 PARK PLACE,...,0,0,0,0,1931,2,C6,630000,1/10/17 0:00,Brooklyn
35721,10370,3,DOWNTOWN-METROTECH,10 COOPS - ELEVATOR APARTMENTS,2,86,11,,D4,270 JAY STREET,...,0,0,0,0,1950,2,D4,329000,10/19/16 0:00,Brooklyn
14100,14104,1,UPPER EAST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1545,34,,D4,330 EAST 83RD STREET,...,0,0,-,-,1925,2,D4,335000,4/10/17 0:00,Manhattan
13347,13351,1,UPPER EAST SIDE (59-79),17 CONDO COOPS,2,1458,1202,,R9,420 EAST 64 STREET,...,0,0,-,-,0,2,R9,838107,3/29/17 0:00,Manhattan
67325,17927,4,MIDDLE VILLAGE,02 TWO FAMILY DWELLINGS,1,2795,42,,B1,58-21 69TH PLACE,...,0,2,2342,2242,1920,1,B1,-,3/28/17 0:00,Queens
64601,15203,4,JAMAICA,02 TWO FAMILY DWELLINGS,1,9812,66,,B3,90-46 178TH STREET,...,0,2,2500,1618,1920,1,B3,-,12/6/16 0:00,Queens
3543,3547,1,GREENWICH VILLAGE-CENTRAL,02 TWO FAMILY DWELLINGS,1,573,18,,S2,48 WEST 10TH STREET,...,1,3,1983,3864,1899,1,S2,10500000,8/1/17 0:00,Manhattan
17287,17291,1,UPPER WEST SIDE (79-96),13 CONDOS - ELEVATOR APARTMENTS,2,1226,1283,,R4,169 WEST 95TH STREET,...,0,1,-,-,1971,2,R4,-,8/7/17 0:00,Manhattan
53096,3698,4,COLLEGE POINT,02 TWO FAMILY DWELLINGS,1,3930,15,,B2,128-18 POWELLS COVE BLVD,...,0,2,3592,1740,2003,1,B2,-,12/7/16 0:00,Queens
83813,7679,5,WEST NEW BRIGHTON,02 TWO FAMILY DWELLINGS,1,216,73,,B9,129 SENECA STREET,...,0,2,2794,1192,2004,1,B9,360000,10/24/16 0:00,Staten Island
22236,3934,2,PARKCHESTER,13 CONDOS - ELEVATOR APARTMENTS,2,3944,2825,,R4,2100 EAST TREMONT AVE,...,0,1,0,0,0,2,R4,99000,11/29/16 0:00,Bronx
30882,5531,3,BROOKLYN HEIGHTS,10 COOPS - ELEVATOR APARTMENTS,2,254,19,,D4,245 HENRY STREET,...,0,0,0,0,1957,2,D4,730000,6/27/17 0:00,Brooklyn
42718,17367,3,MILL BASIN,01 ONE FAMILY DWELLINGS,1,8656,35,,A3,2248 EAST 63RD STREET,...,0,1,5000,3900,1950,1,A3,1790000,5/3/17 0:00,Brooklyn
16860,16864,1,UPPER WEST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1227,1,,D4,400 WEST END AVENUE,...,0,0,-,-,1931,2,D4,-,5/3/17 0:00,Manhattan
10108,10112,1,MURRAY HILL,10 COOPS - ELEVATOR APARTMENTS,2,909,1,,D4,201 EAST 28TH STREET,...,0,0,-,-,1964,2,D4,485000,5/4/17 0:00,Manhattan
53133,3735,4,COLLEGE POINT,02 TWO FAMILY DWELLINGS,1,3985,7,,B1,132-13 11TH AVENUE,...,0,2,1590,2400,1999,1,B1,342500,12/8/16 0:00,Queens
13852,13856,1,UPPER EAST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1513,9,,D4,119 EAST 84TH STREET,...,0,0,-,-,1926,2,D4,800000,8/8/17 0:00,Manhattan
58993,9595,4,FLUSHING-NORTH,44 CONDO PARKING,4,4952,1265,,RG,136-21 LATIMER PLACE,...,0,1,-,-,2013,4,RG,-,4/10/17 0:00,Queens
31147,5796,3,BROWNSVILLE,02 TWO FAMILY DWELLINGS,1,3535,2,,B3,155 GRAFTON STREET,...,0,2,2000,1520,1930,1,B3,189000,10/28/16 0:00,Brooklyn
83718,7584,5,WEST NEW BRIGHTON,01 ONE FAMILY DWELLINGS,1,223,4,,A5,447 CLOVE ROAD,...,0,1,1456,1120,1899,1,A5,112500,9/8/16 0:00,Staten Island
30752,5401,3,BROOKLYN HEIGHTS,09 COOPS - WALKUP APARTMENTS,2C,270,22,,C6,167 CLINTON STREET,...,0,0,0,0,1849,2,C6,1520000,7/20/17 0:00,Brooklyn
51219,1821,4,BAYSIDE,01 ONE FAMILY DWELLINGS,1,7463,50,,A1,58-19 212TH STREET,...,0,1,4116,1248,1950,1,A1,808888,12/19/16 0:00,Queens
55434,6036,4,FAR ROCKAWAY,01 ONE FAMILY DWELLINGS,1,15571,153,,A1,786 CAFFREY AVENUE,...,0,1,4052,1472,1955,1,A1,895000,5/1/17 0:00,Queens
39306,13955,3,FLATLANDS,02 TWO FAMILY DWELLINGS,1,7869,31,,B3,2197 TROY AVENUE,...,0,2,2700,1300,1920,1,B3,450000,11/29/16 0:00,Brooklyn
79748,3614,5,MARINERS HARBOR,05 TAX CLASS 1 VACANT LAND,1B,1234,93,,V0,370 UNION AVENUE,...,0,0,2800,-,0,1,V0,-,12/9/16 0:00,Staten Island
78284,2150,5,GREAT KILLS,01 ONE FAMILY DWELLINGS,1,4447,67,,A5,20D FRANKLIN LANE,...,0,1,960,576,1986,1,A5,322500,12/2/16 0:00,Staten Island
4722,4726,1,GREENWICH VILLAGE-WEST,13 CONDOS - ELEVATOR APARTMENTS,2,640,1037,,R4,400 WEST 12TH STREET,...,0,1,-,-,2007,2,R4,4500000,1/4/17 0:00,Manhattan
570,574,1,CHELSEA,13 CONDOS - ELEVATOR APARTMENTS,2,699,1261,,R4,540 WEST 28TH STREET,...,0,1,-,-,2009,2,R4,1275000,3/1/17 0:00,Manhattan
14005,14009,1,UPPER EAST SIDE (79-96),10 COOPS - ELEVATOR APARTMENTS,2,1529,31,,D4,238 EAST 84TH STREET,...,0,0,-,-,1962,2,D4,425000,10/18/16 0:00,Manhattan
39556,14205,3,FORT GREENE,13 CONDOS - ELEVATOR APARTMENTS,2,2111,1120,,R4,1 HANSON PL,...,0,1,0,0,0,2,R4,1600000,3/3/17 0:00,Brooklyn

In [6]:
#making new column with full address

real_estate_df["Full_Address"] = real_estate_df["ADDRESS"] + " "  + real_estate_df["borough_name"]

real_estate_df.head(50)

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE,borough_name,Full_Address
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,...,5,1633,6440,1900,2,C2,6625000,7/19/17 0:00,Manhattan,153 AVENUE B Manhattan
1,5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,...,31,4616,18690,1900,2,C7,-,12/14/16 0:00,Manhattan,234 EAST 4TH STREET Manhattan
2,6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,...,17,2212,7803,1900,2,C7,-,12/9/16 0:00,Manhattan,197 EAST 3RD STREET Manhattan
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,...,10,2272,6794,1913,2,C4,3936272,9/23/16 0:00,Manhattan,154 EAST 7TH STREET Manhattan
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,...,6,2369,4615,1900,2,C2,8000000,11/17/16 0:00,Manhattan,301 EAST 10TH STREET Manhattan
5,9,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,405,16,,C4,516 EAST 12TH STREET,...,20,2581,9730,1900,2,C4,-,7/20/17 0:00,Manhattan,516 EAST 12TH STREET Manhattan
6,10,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,406,32,,C4,210 AVENUE B,...,8,1750,4226,1920,2,C4,3192840,9/23/16 0:00,Manhattan,210 AVENUE B Manhattan
7,11,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,407,18,,C7,520 EAST 14TH STREET,...,46,5163,21007,1900,2,C7,-,7/20/17 0:00,Manhattan,520 EAST 14TH STREET Manhattan
8,12,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,379,34,,D5,141 AVENUE D,...,15,1534,9198,1920,2,D5,-,6/20/17 0:00,Manhattan,141 AVENUE D Manhattan
9,13,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,387,153,,D9,629 EAST 5TH STREET,...,24,4489,18523,1920,2,D9,16232000,11/7/16 0:00,Manhattan,629 EAST 5TH STREET Manhattan
10,14,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,394,44,,D7,181 AVENUE C,...,34,4295,21328,1910,2,D7,-,7/20/17 0:00,Manhattan,181 AVENUE C Manhattan
11,15,1,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2B,400,21,,D1,530-532 EAST 5TH STREET,...,10,3717,12350,2009,2,D1,10350000,10/17/16 0:00,Manhattan,530-532 EAST 5TH STREET Manhattan
12,16,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,40,,C6,327 EAST 3RD STREET,...,0,-,-,1920,2,C6,1,9/6/16 0:00,Manhattan,327 EAST 3RD STREET Manhattan
13,17,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,40,,C6,327 EAST 3RD STREET,...,0,-,-,1920,2,C6,499000,3/10/17 0:00,Manhattan,327 EAST 3RD STREET Manhattan
14,18,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,40,,C6,327 EAST 3RD STREET,...,0,-,-,1920,2,C6,10,4/28/17 0:00,Manhattan,327 EAST 3RD STREET Manhattan
15,19,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,40,,C6,327 EAST 3RD STREET,...,0,-,-,1920,2,C6,529500,6/9/17 0:00,Manhattan,327 EAST 3RD STREET Manhattan
16,20,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,40,,C6,327 EAST 3RD STREET,...,0,-,-,1920,2,C6,423000,7/14/17 0:00,Manhattan,327 EAST 3RD STREET Manhattan
17,21,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,46,,C6,317 EAST 3RD STREET,...,0,-,-,1925,2,C6,501000,3/16/17 0:00,Manhattan,317 EAST 3RD STREET Manhattan
18,22,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,49,,C6,311 EAST 3RD STREET,...,0,-,-,1920,2,C6,450000,9/1/16 0:00,Manhattan,311 EAST 3RD STREET Manhattan
19,23,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,373,49,,C6,311 EAST 3RD,...,0,-,-,1920,2,C6,510000,8/17/17 0:00,Manhattan,311 EAST 3RD Manhattan
20,24,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,374,8,,C6,702 EAST 5TH STREET,...,0,-,-,1900,2,C6,-,9/7/16 0:00,Manhattan,702 EAST 5TH STREET Manhattan
21,25,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,375,30,,C6,742 EAST 6TH STREET,...,0,-,-,1902,2,C6,350000,8/30/17 0:00,Manhattan,742 EAST 6TH STREET Manhattan
22,26,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,14,,C6,244 EAST 7TH STREET,...,24,4131,16776,1928,2,C6,11900000,6/21/17 0:00,Manhattan,244 EAST 7TH STREET Manhattan
23,27,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,14,,C6,244 EAST 7TH STREET,...,0,-,-,1928,2,C6,11900000,6/21/17 0:00,Manhattan,244 EAST 7TH STREET Manhattan
24,28,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,16,,C6,248 EAST 7TH STREET,...,0,-,-,1928,2,C6,350000,1/30/17 0:00,Manhattan,248 EAST 7TH STREET Manhattan
25,29,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,16,,C6,248 EAST 7TH STREET,...,0,-,-,1928,2,C6,404000,7/7/17 0:00,Manhattan,248 EAST 7TH STREET Manhattan
26,30,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,19,,C6,254 EAST 7TH STREET,...,0,-,-,1910,2,C6,535000,6/21/17 0:00,Manhattan,254 EAST 7TH STREET Manhattan
27,31,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,377,54,,C6,267 EAST 7TH ST,...,0,-,-,1920,2,C6,1400000,8/4/17 0:00,Manhattan,267 EAST 7TH ST Manhattan
28,32,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,377,60,,C6,255 EAST 7TH STREET,...,0,-,-,1900,2,C6,866000,1/9/17 0:00,Manhattan,255 EAST 7TH STREET Manhattan
29,33,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,379,15,,C6,414 EAST 10TH STREET,...,0,-,-,1930,2,C6,355000,4/18/17 0:00,Manhattan,414 EAST 10TH STREET Manhattan
30,34,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,379,15,,C6,414 EAST 10TH STREET,...,0,-,-,1930,2,C6,-,6/19/17 0:00,Manhattan,414 EAST 10TH STREET Manhattan
31,35,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,389,21,,C6,206 EAST 7TH STREET,...,0,-,-,1900,2,C6,805000,8/28/17 0:00,Manhattan,206 EAST 7TH STREET Manhattan
32,36,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,389,49,,C6,623 EAST 6TH STREET,...,0,-,-,1910,2,C6,475000,5/10/17 0:00,Manhattan,623 EAST 6TH STREET Manhattan
33,37,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,389,50,,C6,621 EAST 6TH STREET,...,0,-,-,1920,2,C6,450000,12/2/16 0:00,Manhattan,621 EAST 6TH STREET Manhattan
34,38,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,389,50,,C6,621 EAST 6TH STREET,...,0,-,-,1920,2,C6,450000,1/31/17 0:00,Manhattan,621 EAST 6TH STREET Manhattan
35,39,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,390,55,,C6,199 EAST 7TH STREET,...,0,-,-,1935,2,C6,810000,6/28/17 0:00,Manhattan,199 EAST 7TH STREET Manhattan
36,40,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,391,14,,C6,616 EAST 9TH STREET,...,0,-,-,1910,2,C6,-,12/7/16 0:00,Manhattan,616 EAST 9TH STREET Manhattan
37,41,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,391,14,,C6,618 EAST 9TH STREET,...,0,-,-,1910,2,C6,300000,8/24/17 0:00,Manhattan,618 EAST 9TH STREET Manhattan
38,42,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,391,14,,C6,620 EAST 9TH STREET,...,0,-,-,1910,2,C6,300000,8/30/17 0:00,Manhattan,620 EAST 9TH STREET Manhattan
39,43,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,391,48,,C6,323 EAST 8TH STREET,...,0,-,-,1910,2,C6,579000,6/27/17 0:00,Manhattan,323 EAST 8TH STREET Manhattan
40,44,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,391,57,,C6,303 EAST 8TH STREET,...,0,-,-,1900,2,C6,1500000,3/17/17 0:00,Manhattan,303 EAST 8TH STREET Manhattan
41,45,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2C,393,39,,C6,163 AVENUE C,...,0,-,-,1900,2,C6,25000,6/14/17 0:00,Manhattan,163 AVENUE C Manhattan
42,46,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,394,52,,C6,633 EAST 11TH STREET,...,0,-,-,1937,2,C6,512000,1/17/17 0:00,Manhattan,633 EAST 11TH STREET Manhattan
43,47,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,394,52,,C6,633 EAST 11TH STREET,...,0,-,-,1937,2,C6,410000,1/11/17 0:00,Manhattan,633 EAST 11TH STREET Manhattan
44,48,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,394,52,,C6,633 EAST 11TH STREET,...,0,-,-,1937,2,C6,500000,4/21/17 0:00,Manhattan,633 EAST 11TH STREET Manhattan
45,49,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,394,52,,C6,633 E 11TH ST,...,0,-,-,1937,2,C6,510000,6/29/17 0:00,Manhattan,633 E 11TH ST Manhattan
46,50,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,396,20,,C6,634 EAST 14TH STREET,...,0,-,-,1920,2,C6,475000,10/5/16 0:00,Manhattan,634 EAST 14TH STREET Manhattan
47,51,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,396,20,,C6,634 EAST 14TH STREET,...,0,-,-,1920,2,C6,789019,2/2/17 0:00,Manhattan,634 EAST 14TH STREET Manhattan
48,52,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,396,20,,C6,626 EAST 14TH STREET,...,0,-,-,1920,2,C6,-,3/20/17 0:00,Manhattan,626 EAST 14TH STREET Manhattan
49,53,1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,396,20,,C6,632 EAST 14TH STREET,...,0,-,-,1920,2,C6,-,3/20/17 0:00,Manhattan,632 EAST 14TH STREET Manhattan

In [7]:
#create lat and long columns 

geolocator = Nominatim(user_agent="user_agent")
location = geolocator.geocode("327 EAST 3rd STREET Manhattan")

print((location.latitude, location.longitude))

(40.7208628, -73.9784408)

In [10]:
lat = []
long = []

geolocator = Nominatim(user_agent="user_agent")

for x in real_estate_df["Full_Address"]:
    
    addr = geolocator.geocode(x, timeout=10)    
    if addr is None:
        lat.append(None)
#         long.append(None)
    else:
        latitude = addr.latitude
#         longitude = addr.longitude  
    
    lat.append(latitude)
    long.append(longitude)

real_estate_df['latitude'] = lat
# real_estate_df['longitude'] = long

KeyboardInterrupt:

In [ ]:
real_estate_df.head()

In [ ]:
#picking columns and assigning to new dataframe
real_estate_cols = ['Full_Address','NEIGHBORHOOD', 'TAX CLASS AT PRESENT',
                   'ZIP CODE', 'SALE PRICE', 'BUILDING CLASS AT TIME OF SALE', 'borough_name']

real_estate_clean_df = real_estate_df[real_estate_cols]


real_estate_clean_df.sample(50)

In [ ]:
# #import requests to get lat long for each address
# import requests

# response = requests.get('https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA')

# resp_json_payload = response.json()

# print(resp_json_payload['results'][0]['geometry']['location'])